Repository phac-nml/irida-next, pull requests merged in 2023-10, with the labels that each got.

#205 Fix card preview and update tests
  app/components/viral/card/section_component.html.erb
  test/components/previews/viral_card_component_preview/section_with_action.html.erb
  test/components/previews/viral_card_component_preview/with_header_actions.html.erb
  test/components/previews/viral_card_component_preview/with_multiple_sections.html.erb
  test/components/viral/card_component_test.rb
  test/components/viral/viral_card_component_test.rb
Labels: bug, ready for review

#219 Sample metadata provenance column
  db/migrate/20230929194603_add_metadata_provenance_to_samples.rb
  db/schema.rb
  test/models/sample_test.rb
Labels: ready for review

#234 Allow controller to indicate selected navigation menu item
  app/components/layout/sidebar/item_component.html.erb
  app/components/layout/sidebar/item_component.rb
  app/controllers/dashboard/groups_controller.rb
  app/controllers/dashboard/projects_controller.rb
  app/controllers/groups/members_controller.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/profiles/accounts_controller.rb
  app/controllers/profiles/application_controller.rb
  app/controllers/profiles/passwords_controller.rb
  app/controllers/profiles/personal_access_tokens_controller.rb
  app/controllers/profiles/preferences_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/projects/members_controller.rb
  app/controllers/projects/samples_controller.rb
  app/controllers/projects_controller.rb
  app/views/layouts/application.html.erb
  app/views/layouts/groups.html.erb
  app/views/layouts/profiles.html.erb
  app/views/layouts/projects.html.erb
  test/components/layout_component_test.rb
Labels: ready for review

#237 Sign in enhancements
  app/controllers/sessions_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new_with_no_providers.html.erb
  app/views/devise/sessions/new_with_providers.html.erb
  app/views/devise/shared/_form.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/devise.html.erb
  config/locales/devise.en.yml
  config/locales/en.yml
  storage/.keep
  test/system/profile_test.rb
  test/system/sessions_test.rb
Labels: ready for review

#227 Details Page Shared projects tab
  app/assets/icons/heroicons/document_text.svg
  app/components/viral/empty_state_component.html.erb
  app/components/viral/empty_state_component.rb
  app/controllers/groups/shared_projects_controller.rb
  app/controllers/groups/subgroups_controller.rb
  app/controllers/groups_controller.rb
  app/helpers/view_helper.rb
  app/models/group.rb
  app/views/dashboard/projects/index.turbo_stream.erb
  app/views/groups/shared_projects/index.turbo_stream.erb
  app/views/groups/show.html.erb
  app/views/groups/subgroups/index.turbo_stream.erb
  app/views/groups/subgroups/subgroup.turbo_stream.erb
  app/views/layouts/partials/_empty_content.html.erb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/shared/project/_row.html.erb
  config/locales/en.yml
  config/routes/group.rb
  test/components/previews/viral_empty_component_preview.rb
  test/components/previews/viral_empty_component_preview/default.html.erb
  test/components/viral/empty_component_test.rb
  test/controllers/groups/shared_projects_controller_test.rb
  test/controllers/groups/subgroups_controller_test.rb
  test/controllers/groups_controller_test.rb
  test/fixtures/groups.yml
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
Labels: ready for review

#242 Fixed adding classes on attachment upload error
  app/javascript/controllers/attachment_upload_controller.js
Labels: ready for review

#243 Attachments Concatenation Service
  app/models/attachment.rb
  app/services/attachments/concatenation_service.rb
  app/services/attachments/create_service.rb
  app/validators/attachment_checksum_validator.rb
  config/locales/en.yml
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/files/08-5578-small_S1_L001_R1_001.fastq
  test/fixtures/files/08-5578-small_S1_L001_R2_001.fastq
  test/fixtures/files/08-5923-small_S1_L001_R1_001.fastq
  test/fixtures/files/08-5923-small_S1_L001_R2_001.fastq
  test/fixtures/files/test_file_14.fastq.gz
  test/fixtures/files/test_file_D.fastq
  test/fixtures/files/test_file_fwd_1.fastq
  test/fixtures/files/test_file_fwd_2.fastq
  test/fixtures/files/test_file_fwd_3.fastq
  test/fixtures/files/test_file_rev_1.fastq
  test/fixtures/files/test_file_rev_2.fastq
  test/fixtures/files/test_file_rev_3.fastq
  test/fixtures/samples.yml
  test/services/attachments/concatenation_service_test.rb
Labels: enhancement, ready for review

#264 Fix for memberships on group transfer
  app/models/member.rb
  app/services/groups/transfer_service.rb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/routes.yml
  test/policies/group_policy_test.rb
  test/services/groups/transfer_service_test.rb
  test/system/groups/members_test.rb
Labels: ready for review
