Repository phac-nml/irida-next, pull requests merged in 2023-06, with the labels that each got.

#104 Update: Viral Button Component
  app/assets/icons/heroicons/chevron_up.svg
  app/assets/stylesheets/application.tailwind.css
  app/components/viral/button_component.html.erb
  app/components/viral/button_component.rb
  app/helpers/view_helper.rb
  test/components/previews/viral_button_component_preview.rb
  test/components/previews/viral_button_component_preview/basic.html.erb
  test/components/previews/viral_button_component_preview/destructive.html.erb
  test/components/previews/viral_button_component_preview/disclosure.html.erb
  test/components/previews/viral_button_component_preview/full_width.html.erb
  test/components/previews/viral_button_component_preview/large.html.erb
  test/components/previews/viral_button_component_preview/primary.html.erb
  test/components/previews/viral_button_component_preview/small.html.erb
  test/components/viral/button_component_test.rb
Labels: enhancement, ready for review

#120 chore: Default PR template and added link to PR acceptance checklist
  .github/pull_request_template.md
Labels: ready for review

#116 Upgrade: Updated modal to have action buttons and JavaScript open
  app/assets/stylesheets/application.tailwind.css
  app/components/viral/dialog/header_component.html.erb
  app/components/viral/dialog/header_component.rb
  app/components/viral/dialog/section_component.html.erb
  app/components/viral/dialog/section_component.rb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  app/components/viral/dialog_component_controller.js
  app/components/viral/modal_component.html.erb
  app/components/viral/modal_component.rb
  app/components/viral/modal_component_controller.js
  app/helpers/view_helper.rb
  config/locales/en.yml
  test/components/previews/viral_dialog_component_preview.rb
  test/components/previews/viral_dialog_component_preview/confirmation.html.erb
  test/components/previews/viral_dialog_component_preview/default.html.erb
  test/components/previews/viral_dialog_component_preview/extra_large.html.erb
  test/components/previews/viral_dialog_component_preview/large.html.erb
  test/components/previews/viral_dialog_component_preview/small.html.erb
  test/components/previews/viral_dialog_component_preview/with_action_buttons.html.erb
  test/components/previews/viral_dialog_component_preview/with_multiple_sections.html.erb
  test/components/previews/viral_dialog_component_preview/with_trigger.html.erb
  test/components/previews/viral_modal_component_preview.rb
  test/components/previews/viral_modal_component_preview/default.html.erb
  test/components/previews/viral_modal_component_preview/extra_large.html.erb
  test/components/previews/viral_modal_component_preview/large.html.erb
  test/components/previews/viral_modal_component_preview/small.html.erb
  test/components/viral/system/dialog_component_test.rb
  test/components/viral/system/modal_component_test.rb
Labels: enhancement, ready for review

#109 Feature: Auditing
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/member.rb
  app/models/namespace.rb
  app/models/personal_access_token.rb
  app/models/sample.rb
  app/models/user.rb
  config/application.rb
  db/functions/logidze_capture_exception_v01.sql
  db/functions/logidze_compact_history_v01.sql
  db/functions/logidze_filter_keys_v01.sql
  db/functions/logidze_logger_v03.sql
  db/functions/logidze_snapshot_v03.sql
  db/functions/logidze_version_v02.sql
  db/migrate/20230519155459_logidze_install.rb
  db/migrate/20230519155460_enable_hstore.rb
  db/migrate/20230519155615_add_logidze_to_namespaces.rb
  db/migrate/20230519155734_add_logidze_to_members.rb
  db/migrate/20230519155837_add_logidze_to_samples.rb
  db/migrate/20230519155844_add_logidze_to_personal_access_tokens.rb
  db/migrate/20230519155854_add_logidze_to_users.rb
  db/schema.rb
  db/triggers/logidze_on_members_v01.sql
  db/triggers/logidze_on_namespaces_v01.sql
  db/triggers/logidze_on_personal_access_tokens_v01.sql
  db/triggers/logidze_on_samples_v01.sql
  db/triggers/logidze_on_users_v01.sql
  test/services/groups/create_service_test.rb
  test/services/groups/update_service_test.rb
  test/services/members/create_service_test.rb
  test/services/members/update_service_test.rb
  test/services/projects/create_service_test.rb
  test/services/projects/transfer_service_test.rb
  test/services/projects/update_service_test.rb
  test/services/samples/create_service_test.rb
  test/services/samples/update_service_test.rb
Labels: enhancement, database, ready for review

#118 Selection controller
  app/javascript/controllers/selection_controller.js
  test/components/previews/selection_preview.rb
  test/components/previews/selection_preview/default.html.erb
  test/components/previews/selection_preview/with_a_storage_key.html.erb
  test/components/previews/selection_preview/within_a_table.html.erb
  test/components/viral/system/selection_test.rb
Labels: enhancement, ready for review

#125 update: Confirm form confirmation
  app/components/confirmation_component.html.erb
  app/components/confirmation_component_controller.js
  app/javascript/application.js
  config/locales/en.yml
  test/components/previews/confirmation_component_preview.rb
  test/components/previews/confirmation_component_preview/with_confirm_value.html.erb
  test/components/previews/confirmation_component_preview/with_custom_form.html.erb
  test/components/viral/system/confirmation_component_test.rb
Labels: enhancement, ready for review

#122 Authentication: Use Rails Credentials for storing auth providers credentials
  .gitignore
  Gemfile
  Gemfile.lock
  config/application.yml
  config/initializers/devise.rb
Labels: security, ready for review

#113 Feature: Soft Delete Records
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/membership_actions.rb
  app/controllers/groups_controller.rb
  app/controllers/projects/samples_controller.rb
  app/controllers/projects_controller.rb
  app/models/member.rb
  app/models/namespace.rb
  app/models/personal_access_token.rb
  app/models/project.rb
  app/models/route.rb
  app/models/sample.rb
  app/models/user.rb
  app/views/groups/members/index.html.erb
  app/views/projects/members/index.html.erb
  db/migrate/20230530204556_add_deleted_at_to_namespaces.rb
  db/migrate/20230530204607_add_deleted_at_to_members.rb
  db/migrate/20230530204615_add_deleted_at_to_samples.rb
  db/migrate/20230530204734_add_deleted_at_to_users.rb
  db/migrate/20230530204753_add_deleted_at_to_personal_access_tokens.rb
  db/migrate/20230530205431_add_deleted_at_to_routes.rb
  db/migrate/20230601145011_add_deleted_at_to_projects.rb
  db/migrate/20230622175923_modify_index_on_samples.rb
  db/migrate/20230622204135_modify_index_on_members.rb
  db/migrate/20230626190220_modify_index_on_routes.rb
  db/migrate/20230628145212_modify_index_on_users.rb
  db/schema.rb
  db/seeds.rb
  test/models/group_test.rb
  test/models/members/group_member_test.rb
  test/models/members/project_member_test.rb
  test/models/namespaces/project_namespace_test.rb
  test/models/sample_test.rb
  test/system/groups/members_test.rb
  test/system/projects/members_test.rb
Labels: database, ready for review

#119 Update: Membership source
  Gemfile
  Gemfile.lock
  app/components/updated_component.html.erb
  app/components/updated_component.rb
  app/controllers/concerns/membership_actions.rb
  app/helpers/members_helper.rb
  app/policies/member_policy.rb
  app/views/groups/members/index.html.erb
  app/views/groups/members/update.turbo_stream.erb
  app/views/projects/members/index.html.erb
  app/views/projects/members/update.turbo_stream.erb
  config/locales/en.yml
  test/components/previews/updated_component_preview.rb
  test/components/previews/updated_component_preview/default.html.erb
  test/components/previews/updated_component_preview/with_custom_description.html.erb
  test/components/updated_component_test.rb
  test/fixtures/members.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/policies/project_policy_test.rb
  test/system/groups/members_test.rb
  test/system/projects/members_test.rb
  test/system/projects_test.rb
Labels: enhancement, ready for review

#117 Transfer samples service
  app/models/member.rb
  app/policies/project_policy.rb
  app/services/samples/transfer_service.rb
  config/locales/en.yml
  docs-site/docs/user/organization/members/member-permissions.md
  test/policies/project_policy_test.rb
  test/services/samples/transfer_service_test.rb
Labels: enhancement, ready for review

#124 Member leave group
  app/controllers/concerns/membership_actions.rb
  app/models/member.rb
  app/services/members/destroy_service.rb
  app/views/groups/members/_current_user_is_member.html.erb
  app/views/groups/members/_current_user_is_not_member.html.erb
  app/views/groups/members/index.html.erb
  app/views/projects/members/_current_user_is_member.html.erb
  app/views/projects/members/_current_user_is_not_member.html.erb
  app/views/projects/members/index.html.erb
  config/locales/en.yml
  test/models/members/group_member_test.rb
  test/policies/project_policy_test.rb
  test/services/members/destroy_service_test.rb
  test/system/groups/members_test.rb
  test/system/projects/members_test.rb
Labels: enhancement, ready for review

#99 Update: Updated UI for transfering a project namespace
  app/assets/stylesheets/application.tailwind.css
  app/components/viral/button_component.rb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  app/controllers/projects_controller.rb
  app/javascript/controllers/application.js
  app/javascript/controllers/projects/transfer_controller.js
  app/services/projects/transfer_service.rb
  app/views/layouts/devise.html.erb
  app/views/layouts/projects.html.erb
  app/views/profiles/personal_access_tokens/_form.html.erb
  app/views/projects/_transfer.html.erb
  app/views/projects/_transfer_form.html.erb
  app/views/projects/edit.html.erb
  app/views/projects/transfer.turbo_stream.erb
  config/locales/en.yml
  test/components/previews/viral_button_component_preview/destructive.html.erb
  test/components/previews/viral_button_component_preview/primary.html.erb
  test/components/viral/button_component_test.rb
  test/controllers/projects_controller_test.rb
  test/system/projects/transfer_test.rb
  test/system/projects_test.rb
Labels: enhancement, ready for review
