Repository phac-nml/irida-next, pull requests merged in 2023-12, with the labels that each got.

#310 Fix broken seeds.rb file and add logging
  db/seeds.rb
  docs-site/docs/development/useful_commands.md
  lib/tasks/debug.rake
  scripts/clean_dev.sh
  test/fixtures/files/test_file_D.fastq
Labels: bug, ready for review

#312 Project Sample Metadata: Metadata summary db representation
  db/migrate/20231121200855_add_metadata_summary_to_namespaces.rb
  db/schema.rb
  test/fixtures/groups.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/models/group_test.rb
  test/models/namespaces/project_namespace_test.rb
Labels: database

#324 Active jobs Backend
  .gitattributes
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/jobs/attachments_cleanup_job.rb
  app/models/jobs_record.rb
  config/application.rb
  config/database.yml
  config/initializers/good_job.rb
  db/jobs_migrate/20231208184638_create_good_jobs.rb
  db/jobs_schema.rb
  scripts/clean_dev.sh
  test/jobs/attachments_cleanup_job_test.rb
Labels: enhancement, database, ready for review

#320 Concatenation file format fix
  app/services/attachments/concatenation_service.rb
  app/views/projects/samples/attachments/concatenations/_modal.html.erb
  config/locales/en.yml
  db/schema.rb
  test/application_system_test_case.rb
  test/services/attachments/concatenation_service_test.rb
  test/system/projects/samples_test.rb
  test/test_helpers/html5_helpers.rb
Labels: bug

#332 Workflow Listings
  app/assets/icons/heroicons/command_line.svg
  app/components/layout_component.html.erb
  app/controllers/workflow_executions_controller.rb
  app/views/layouts/application.html.erb
  app/views/workflow_executions/index.html.erb
  config/locales/en.yml
  config/routes.rb
  config/routes/dashboard.rb
  db/seeds.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#337 Redirect after successful workflow submission
  app/components/nextflow_component.html.erb
  app/controllers/workflow_executions_controller.rb
  test/controllers/workflow_executions_controller_test.rb
Labels: enhancement

#328 Workflow Executions Cancellation Service
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancelation_service.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/services/workflow_executions/cancelation_service_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement, ready for review

#340 Member expiration frontend
  app/models/member.rb
  app/views/groups/members/_create_modal.html.erb
  app/views/groups/members/_member.html.erb
  app/views/groups/members/_member_listing.html.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/members/_member.html.erb
  app/views/projects/members/_member_listing.html.erb
  config/locales/en.yml
  test/system/groups/members_test.rb
  test/system/projects/members_test.rb
Labels: ready for review
