Repository phac-nml/irida-next, pull requests merged in 2023-08, with the labels that each got.

#138 Namespace to group controller service
  app/controllers/concerns/share_actions.rb
  app/controllers/groups_controller.rb
  app/controllers/projects_controller.rb
  app/models/member.rb
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/services/namespaces/group_share_service.rb
  app/services/namespaces/group_unshare_service.rb
  config/locales/en.yml
  config/routes/group.rb
  config/routes/project.rb
  test/controllers/concerns/share_actions_concern_test.rb
  test/controllers/groups_controller_test.rb
  test/controllers/projects_controller_test.rb
  test/fixtures/routes.yml
  test/policies/group_policy_test.rb
  test/policies/namespaces/project_namespace_policy_test.rb
  test/services/namespaces/group_share_service_test.rb
  test/services/namespaces/group_unshare_service_test.rb
Labels: enhancement, ready for review

#121 Group Advanced Settings - Transfer
  app/controllers/groups_controller.rb
  app/javascript/controllers/transfer_controller.js
  app/policies/group_policy.rb
  app/services/base_group_service.rb
  app/services/groups/transfer_service.rb
  app/views/groups/_edit_advanced_transfer.html.erb
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/edit.html.erb
  app/views/groups/transfer.turbo_stream.erb
  app/views/projects/_transfer.html.erb
  app/views/projects/_transfer_form.html.erb
  config/locales/en.yml
  config/routes/group.rb
  test/controllers/groups_controller_test.rb
  test/fixtures/groups.yml
  test/policies/group_policy_test.rb
  test/services/groups/transfer_service_test.rb
  test/system/groups_test.rb
Labels: enhancement, ready for review

#143 Delete project
  app/controllers/projects_controller.rb
  app/views/projects/_destroy.html.erb
  app/views/projects/_transfer.html.erb
  app/views/projects/edit.html.erb
  app/views/projects/index.html.erb
  app/views/projects/index.turbo_stream.erb
  config/locales/en.yml
  test/controllers/projects_controller_test.rb
  test/system/projects_test.rb
Labels: enhancement, ready for review

#134 Updatable User fields, local and omniauth
  .vscode/launch.json
  app/assets/stylesheets/application.tailwind.css
  app/controllers/profiles/passwords_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/registrations_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/profiles.html.erb
  app/views/profiles/_domain_user.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/passwords/edit.html.erb
  app/views/profiles/show.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/en.yml
  db/migrate/20230630162646_add_user_attributes.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/profiles/passwords_controller_test.rb
  test/controllers/profiles_controller_test.rb
  test/fixtures/users.yml
  test/test_helpers/omniauth_helpers.rb
Labels: enhancement, database

#141 GraphQL: Namespace Project linkage
  app/graphql/resolvers/namespace_projects_resolver.rb
  app/graphql/resolvers/namespace_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/group_type.rb
  app/graphql/types/namespace.rb
  app/graphql/types/namespace_type.rb
  app/graphql/types/project_type.rb
  app/graphql/types/query_type.rb
  app/policies/namespaces/user_namespace_policy.rb
  test/graphql/namespace_query_test.rb
Labels: enhancement, graphql

#148 NamespaceGroupLink updating
  app/controllers/concerns/share_actions.rb
  app/models/member.rb
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/services/namespaces/group_share_update_service.rb
  config/locales/en.yml
  config/routes/group.rb
  config/routes/project.rb
  test/controllers/groups_controller_test.rb
  test/controllers/projects_controller_test.rb
  test/policies/group_policy_test.rb
  test/policies/namespaces/project_namespace_policy_test.rb
  test/services/namespaces/group_share_update_service_test.rb
Labels: enhancement

#144 Project change path
  app/views/projects/_change_path.html.erb
  app/views/projects/_transfer.html.erb
  app/views/projects/edit.html.erb
  config/locales/en.yml
  test/system/projects_test.rb
Labels: enhancement, ready for review
