Repository phac-nml/irida-next, pull requests merged in 2023-11, with the labels that each got.

#295 Fix: Missing Projects in Projects Dashboard where user is a member
  app/controllers/dashboard/projects_controller.rb
  app/policies/project_policy.rb
  test/controllers/concerns/projects_membership_actions_concern_test.rb
  test/fixtures/members.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/routes.yml
  test/fixtures/users.yml
  test/services/projects/destroy_service_test.rb
  test/system/dashboard/projects_test.rb
Labels: ready for review

#298 Update: Concatenation Service
  app/services/attachments/concatenation_service.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/files/test-fq-file2_S1_L001_R1_001.fq
  test/fixtures/files/test-fq-file2_S1_L001_R1_001.fq.gz
  test/fixtures/files/test-fq-file2_S1_L001_R2_001.fq
  test/fixtures/files/test-fq-file_S1_L001_R1_001.fq
  test/fixtures/files/test-fq-file_S1_L001_R1_001.fq.gz
  test/fixtures/files/test-fq-file_S1_L001_R2_001.fq
  test/services/attachments/concatenation_service_test.rb
Labels: enhancement, ready for review

#301 style: Fix checkbox colour for project samples
  app/views/projects/samples/_table.html.erb
Labels: enhancement, ready for review

#240 Ga4gh WES Api Integration
  Gemfile
  Gemfile.lock
  docs-site/docs/configuration/_category_.json
  docs-site/docs/configuration/ga4gh_wes.md
  docs-site/docs/development/integration/_category_.json
  docs-site/docs/development/integration/ga4gh_wes_setup.md
  docs-site/docs/development/useful_commands.md
  lib/integrations/api_exceptions.rb
  lib/integrations/ga4gh_wes_api/v1/api_connection.rb
  lib/integrations/ga4gh_wes_api/v1/api_requester.rb
  lib/integrations/ga4gh_wes_api/v1/client.rb
  lib/tasks/ga4gh_wes.rake
  test/integration/ga4gh_wes_api_test.rb
Labels: documentation, enhancement, security, ready for review

#292 Workflow submission routes
  app/assets/icons/heroicons/rocket_launch.svg
  app/controllers/workflow_executions/submissions_controller.rb
  app/controllers/workflow_executions_controller.rb
  app/views/projects/samples/index.html.erb
  app/views/workflow_executions/submissions/pipeline_selection.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  config/routes/workflow_executions.rb
  test/controllers/workflow_executions/submission_controller_test.rb
Labels: ready for review

#263 Fix for memberships on group transfer job
  app/jobs/update_memberships_job.rb
  app/models/member.rb
  app/services/groups/transfer_service.rb
  app/services/members/update_service.rb
  test/fixtures/groups.yml
  test/fixtures/routes.yml
  test/jobs/update_memberships_job_test.rb
  test/services/groups/transfer_service_test.rb
  test/services/members/update_service_test.rb
  test/test_helper.rb
Labels: ready for review

#305 Disable table action links if no samples are seleceted
  app/javascript/controllers/action_link_controller.js
  app/javascript/controllers/selection_controller.js
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/index.html.erb
Labels: ready for review

#294 Attachments Concatenation UI
  app/assets/stylesheets/application.tailwind.css
  app/components/viral/card/header_component.html.erb
  app/controllers/projects/samples/attachments/concatenations_controller.rb
  app/controllers/projects/samples/attachments_controller.rb
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/projects/samples/attachments/concatenations_controller.js
  app/javascript/controllers/selection_controller.js
  app/services/attachments/concatenation_service.rb
  app/views/projects/samples/attachments/_attachment.html.erb
  app/views/projects/samples/attachments/_new_attachment_modal.html.erb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/samples/attachments/concatenations/_modal.html.erb
  app/views/projects/samples/attachments/concatenations/create.turbo_stream.erb
  app/views/projects/samples/attachments/create.turbo_stream.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/routes/project.rb
  test/controllers/projects/samples/attachments/concatenations_controller_test.rb
  test/controllers/projects/samples/attachments_controller_test.rb
  test/services/attachments/concatenation_service_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#282 Fix for memberships on project transfer
  app/services/projects/transfer_service.rb
  test/jobs/update_memberships_job_test.rb
  test/policies/group_policy_test.rb
  test/services/groups/transfer_service_test.rb
  test/services/projects/transfer_service_test.rb
  test/services/samples/update_service_test.rb
Labels: ready for review

#300 Workflow selection UI
  app/controllers/workflow_executions/submissions_controller.rb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  app/views/projects/samples/transfers/new.turbo_stream.erb
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  app/views/workflow_executions/submissions/pipeline_selection.turbo_stream.erb
  config/locales/en.yml
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review

#314 Fix issue with the bottom border of the top navigation
  app/components/layout_component.html.erb
Labels: bug, ready for review

#308 Workflow DB Representation
  Gemfile
  Gemfile.lock
  app/models/sample.rb
  app/models/samples_workflow_execution.rb
  app/models/workflow_execution.rb
  config/schemas/workflow_execution_metadata.json
  db/migrate/20231110010253_workflow_execution.rb
  db/migrate/20231110010313_samples_workflow_execution.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/models/samples_workflow_executions_test.rb
  test/models/workflow_execution_test.rb
Labels: database, ready for review
