Repository phac-nml/irida-next, pull requests merged in 2023-09, with the labels that each got.

#145 Dashboard groups
  app/assets/icons/heroicons/arrow_top_right_on_square.svg
  app/assets/stylesheets/application.tailwind.css
  app/components/groups_list/group_list_tree_component.html.erb
  app/components/groups_list/group_list_tree_component.rb
  app/components/groups_list/group_row/row_contents_component.html.erb
  app/components/groups_list/group_row/row_contents_component.rb
  app/components/groups_list/group_row/with_children_component.html.erb
  app/components/groups_list/group_row/with_children_component.rb
  app/components/groups_list/group_row/without_children_component.html.erb
  app/components/groups_list/group_row/without_children_component.rb
  app/components/groups_list/group_row_component.rb
  app/components/groups_list_tree_container_component.rb
  app/components/viral/avatar_component.html.erb
  app/components/viral/avatar_component.rb
  app/controllers/dashboard/groups_controller.rb
  app/controllers/groups_controller.rb
  app/javascript/controllers/groups/row_controller.js
  app/policies/group_policy.rb
  app/views/dashboard/groups/index.html.erb
  app/views/dashboard/groups/index.turbo_stream.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
  config/routes/dashboard.rb
  db/seeds.rb
  test/components/group_list_tree_component_test.rb
  test/controllers/groups_controller_test.rb
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
Labels: enhancement

#167 Attachments: File presence validation
  Gemfile
  Gemfile.lock
  app/controllers/projects/samples/attachments_controller.rb
  app/controllers/projects/samples_controller.rb
  app/models/attachment.rb
  app/views/projects/samples/attachments/_form.html.erb
  test/models/attachment_test.rb
Labels: ready for review

#165 Attachments: Checksum Uniqueness Validation
  app/assets/stylesheets/application.tailwind.css
  app/components/viral/dialog_component.html.erb
  app/models/attachment.rb
  app/validators/attachment_checksum_validator.rb
  app/views/projects/samples/attachments/_form.html.erb
  config/locales/en.yml
  test/controllers/projects/samples/attachments_controller_test.rb
  test/fixtures/files/test_file_1.fastq
  test/models/attachment_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#157 Dark mode move to profile preferences
  app/assets/icons/heroicons/adjustment_horizontal.svg
  app/controllers/profiles/preferences_controller.rb
  app/javascript/controllers/colour_mode_controller.js
  app/javascript/controllers/dark_mode_controller.js
  app/views/layouts/application.html.erb
  app/views/layouts/groups.html.erb
  app/views/layouts/profiles.html.erb
  app/views/layouts/projects.html.erb
  app/views/profiles/preferences/show.html.erb
  app/views/shared/_dark_mode_check.html.erb
  config/locales/en.yml
  config/routes/profile.rb
Labels: ready for review

#158 Move component js to javascript/controllers folder to eliminate console errors
  app/components/clipboard_component.html.erb
  app/components/confirmation_component.html.erb
  app/components/layout/sidebar/header_component.html.erb
  app/components/layout/sidebar_component.html.erb
  app/components/layout_component.html.erb
  app/components/viral/dialog/header_component.html.erb
  app/components/viral/dialog_component.html.erb
  app/components/viral/tooltip_component.html.erb
  app/javascript/controllers/clipboard_controller.js
  app/javascript/controllers/confirmation_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/layout_controller.js
  app/javascript/controllers/viral/dialog_controller.js
  app/javascript/controllers/viral/dropdown_controller.js
  app/javascript/controllers/viral/flash_controller.js
  app/javascript/controllers/viral/tooltip_controller.js
  app/views/dashboard/projects/index.html.erb
  app/views/projects/samples/attachments/_new_attachment_modal.html.erb
  config/importmap.rb
  test/components/previews/viral_dialog_component_preview/confirmation.html.erb
  test/components/previews/viral_dialog_component_preview/with_action_buttons.html.erb
  test/components/previews/viral_dialog_component_preview/with_trigger.html.erb
  test/components/viral/system/tooltip_component_test.rb
Labels: ready for review

#168 Fix field errors
  app/components/viral/form/help_text_component.html.erb
  app/components/viral/form/help_text_component.rb
  app/helpers/view_helper.rb
  app/views/shared/form/_field_errors.html.erb
  test/components/previews/viral_form_help_text_component_preview.rb
  test/components/previews/viral_form_help_text_component_preview/default.html.erb
  test/components/previews/viral_form_help_text_component_preview/error.html.erb
  test/components/previews/viral_form_help_text_component_preview/success.html.erb
  test/components/viral/form/help_text_component_test.rb
Labels: ready for review

#182 Fix documentation links
  README.md
  docs-site/docs/development/development_processes/code_review.md
Labels: documentation, ready for review

#183 Updating sample transfer modal to use turbo_stream
  app/controllers/projects/samples/transfers_controller.rb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/transfers/new.html.erb
  app/views/projects/samples/transfers/new.turbo_stream.erb
  test/controllers/projects/samples/transfers_controller_test.rb
Labels: ready for review

#175 Add graphql support for samples via sample_type and project_samples_resolver
  app/graphql/irida_schema.rb
  app/graphql/resolvers/project_samples_resolver.rb
  app/graphql/resolvers/samples_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/project_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/sample_type.rb
  test/graphql/nodes_query_test.rb
  test/graphql/project_sample_query_test.rb
  test/graphql/samples_query_test.rb
Labels: ready for review, graphql

#178 Namespace group link UI create
  app/components/viral/dialog_component.html.erb
  app/controllers/concerns/share_actions.rb
  app/javascript/controllers/datepicker_controller.js
  app/policies/namespaces/project_namespace_policy.rb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/group_links/_invited_groups.html.erb
  app/views/groups/group_links/_namespace_group_link.html.erb
  app/views/groups/group_links/create.turbo_stream.erb
  app/views/groups/group_links/index.turbo_stream.erb
  app/views/groups/group_links/new.turbo_stream.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/groups/members/create.turbo_stream.erb
  app/views/groups/members/destroy.turbo_stream.erb
  app/views/groups/members/index.html.erb
  app/views/groups/members/new.turbo_stream.erb
  app/views/profiles/personal_access_tokens/_form.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/group_links/_invited_groups.html.erb
  app/views/projects/group_links/create.turbo_stream.erb
  app/views/projects/group_links/index.turbo_stream.erb
  app/views/projects/group_links/new.turbo_stream.erb
  app/views/projects/group_links/update.turbo_stream.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/members/create.turbo_stream.erb
  app/views/projects/members/destroy.turbo_stream.erb
  app/views/projects/members/index.html.erb
  app/views/projects/members/new.turbo_stream.erb
  config/locales/en.yml
  config/routes/group.rb
  config/routes/project.rb
  test/system/groups/group_links_test.rb
  test/system/projects/group_links_test.rb
Labels: ready for review

#173 Fix create project form errors
  app/assets/stylesheets/application.tailwind.css
  app/views/projects/_project_namespace_fields.erb
  app/views/projects/new.html.erb
  config/locales/en.yml
  test/system/projects_test.rb
Labels: ready for review

#189 Fix edit project form errors
  app/views/projects/edit.html.erb
  config/locales/en.yml
  test/system/projects_test.rb
Labels: ready for review

#195 Moved pagination into a partial for members and group_links
  app/views/groups/group_links/_pagination.html.erb
  app/views/groups/group_links/create.turbo_stream.erb
  app/views/groups/group_links/index.turbo_stream.erb
  app/views/groups/members/_pagination.html.erb
  app/views/groups/members/create.turbo_stream.erb
  app/views/groups/members/destroy.turbo_stream.erb
  app/views/groups/members/index.turbo_stream.erb
  app/views/projects/group_links/_pagination.html.erb
  app/views/projects/group_links/index.turbo_stream.erb
  app/views/projects/members/_pagination.html.erb
  app/views/projects/members/destroy.turbo_stream.erb
  app/views/projects/members/index.turbo_stream.erb
Labels: ready for review

#179 Namespace group link UI destroy
  app/controllers/concerns/share_actions.rb
  app/views/groups/group_links/_namespace_group_link.html.erb
  app/views/groups/group_links/destroy.turbo_stream.erb
  app/views/projects/group_links/_namespace_group_link.html.erb
  app/views/projects/group_links/destroy.turbo_stream.erb
  app/views/shared/error/not_authorized.turbo_stream.erb
  config/locales/en.yml
  db/migrate/20230913011402_modify_index_on_namespace_group_links.rb
  db/schema.rb
  test/system/groups/group_links_test.rb
  test/system/projects/group_links_test.rb
Labels: ready for review

#192 Fix group form errors
  app/models/namespace.rb
  app/services/groups/create_service.rb
  app/views/groups/_form_fields.html.erb
  config/locales/en.yml
  test/system/groups_test.rb
Labels: ready for review

#198 Attachments: Direct multiple upload
  app/controllers/projects/samples/attachments_controller.rb
  app/javascript/application.js
  app/services/attachments/create_service.rb
  app/views/projects/samples/attachments/_form.html.erb
  app/views/projects/samples/attachments/_new_attachment_modal.html.erb
  app/views/projects/samples/attachments/create.turbo_stream.erb
  config/application.rb
  config/importmap.rb
  config/locales/en.yml
  config/routes.rb
  test/controllers/projects/samples/attachments_controller_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#200 Datepicker View Component
  app/components/viral/form/datepicker_component.html.erb
  app/components/viral/form/datepicker_component.rb
  app/helpers/view_helper.rb
  app/javascript/controllers/datepicker_controller.js
  test/components/previews/viral_form_datepicker_component_preview.rb
  test/components/previews/viral_form_datepicker_component_preview/default.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_help_text.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_label.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_placeholder.html.erb
  test/components/viral/form/datepicker_component_test.rb
Labels: ready for review

#197 Update sidebar & breadcrumbs when editing project
  app/components/layout_component.html.erb
  app/components/viral/breadcrumb_component.html.erb
  app/controllers/projects_controller.rb
  app/views/layouts/projects.html.erb
  app/views/projects/_change_path.html.erb
  app/views/projects/_edit_name_and_description_form.html.erb
  app/views/projects/edit.html.erb
  app/views/projects/update.turbo_stream.erb
  test/controllers/projects_controller_test.rb
  test/system/projects_test.rb
Labels: ready for review

#193 Nextflow: select input for enums
  app/components/nextflow_component.html.erb
  app/components/viral/form/select/option_component.rb
  app/components/viral/form/select_component.en.yml
  app/components/viral/form/select_component.html.erb
  app/components/viral/form/select_component.rb
  app/helpers/view_helper.rb
  test/components/previews/viral_form_select_component_preview.rb
  test/components/previews/viral_form_select_component_preview/default.html.erb
  test/components/previews/viral_form_select_component_preview/selected_option.html.erb
  test/components/previews/viral_form_select_component_preview/with_help_text.html.erb
  test/components/viral/form/select_component_test.rb
  test/components/viral/form/text_input_component_test.rb
  test/fixtures/files/nextflow/nextflow_schema_with_select_option.json
Labels: ready for review

#217 Viral tabs component
  app/components/viral/tabs/tab_component.rb
  app/components/viral/tabs_component.html.erb
  app/components/viral/tabs_component.rb
  app/helpers/view_helper.rb
  app/views/groups/members/index.html.erb
  app/views/projects/members/index.html.erb
  test/components/previews/viral_tabs_component_preview.rb
  test/components/previews/viral_tabs_component_preview/default.html.erb
  test/components/viral/tabs_component_test.rb
Labels: ready for review
