Repository phac-nml/irida-next, pull requests merged in 2024-11, with the labels that each got.

#826 Workflow Executions: Filter
  app/components/workflow_executions/table_component.html.erb
  app/components/workflow_executions/table_component.rb
  app/controllers/concerns/workflow_execution_actions.rb
  app/models/workflow_execution.rb
  app/views/projects/workflow_executions/_table.html.erb
  app/views/projects/workflow_executions/index.html.erb
  app/views/workflow_executions/_table.html.erb
  app/views/workflow_executions/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/workflow_executions.yml
  test/jobs/data_exports/create_job_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: ready for review

#821 Pathogen Rails UI Library: Initial Setup & Button Component
  Gemfile
  Gemfile.lock
  config/application.rb
  config/tailwind.config.js
  embedded_gems/pathogen/.rubocop.yml
  embedded_gems/pathogen/Gemfile
  embedded_gems/pathogen/Gemfile.lock
  embedded_gems/pathogen/app/components/pathogen/base_button.rb
  embedded_gems/pathogen/app/components/pathogen/base_component.rb
  embedded_gems/pathogen/app/components/pathogen/button.html.erb
  embedded_gems/pathogen/app/components/pathogen/button.rb
  embedded_gems/pathogen/app/components/pathogen/component.rb
  embedded_gems/pathogen/app/components/pathogen/icon.rb
  embedded_gems/pathogen/app/lib/pathogen/button_sizes.rb
  embedded_gems/pathogen/app/lib/pathogen/button_visuals.rb
  embedded_gems/pathogen/app/lib/pathogen/fetch_or_fallback_helper.rb
  embedded_gems/pathogen/app/lib/pathogen/test_selector_helper.rb
  embedded_gems/pathogen/lib/pathogen/view_components.rb
  embedded_gems/pathogen/lib/pathogen/view_components/engine.rb
  embedded_gems/pathogen/lib/pathogen/view_components/version.rb
  embedded_gems/pathogen/pathogen_view_components.gemspec
  test/components/pathogen/base_button_test.rb
  test/components/pathogen/base_component_test.rb
  test/components/pathogen/button_test.rb
  test/components/previews/list_filter_component_preview/default.html.erb
  test/components/previews/pathogen_button_preview.rb
  test/components/previews/pathogen_button_preview/all_schemes.html.erb
  test/components/previews/pathogen_button_preview/leading_visual.html.erb
  test/components/previews/pathogen_button_preview/leading_visual_svg.html.erb
  test/components/previews/pathogen_button_preview/trailing_visual.html.erb
  test/components/previews/pathogen_button_preview/trailing_visual_svg.html.erb
Labels: enhancement

#835 UI Tests: projects samples_count
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/views/shared/project/_row.html.erb
  test/components/activity_component_test.rb
  test/fixtures/activities.yml
  test/system/dashboard/projects_test.rb
  test/system/groups_test.rb
Labels: ready for review

#836 Data Table Component and update to profiles PAT table
  app/components/viral/data_table/column_component.rb
  app/components/viral/data_table_component.html.erb
  app/components/viral/data_table_component.rb
  app/controllers/profiles/personal_access_tokens_controller.rb
  app/helpers/view_helper.rb
  app/views/profiles/personal_access_tokens/_form.html.erb
  app/views/profiles/personal_access_tokens/_personal_access_token.html.erb
  app/views/profiles/personal_access_tokens/_table.html.erb
  app/views/profiles/personal_access_tokens/create.turbo_stream.erb
  app/views/profiles/personal_access_tokens/index.html.erb
  app/views/profiles/personal_access_tokens/revoke.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/viral_data_table_component_preview.rb
  test/components/previews/viral_data_table_component_preview/default.html.erb
  test/components/previews/viral_data_table_component_preview/overflow_x.html.erb
  test/components/viral/system/data_table_component_test.rb
  test/system/profile_test.rb
Labels: ready for review

#844 Pathogen: Tabs
  embedded_gems/pathogen/app/components/pathogen/tabs_panel.html.erb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel.rb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel/count.html.erb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel/count.rb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel/tab.html.erb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel/tab.rb
  test/components/pathogen/tabs_panel_test.rb
  test/components/previews/pathogen_tabs_panel_preview.rb
  test/components/previews/pathogen_tabs_panel_preview/default.html.erb
  test/components/previews/pathogen_tabs_panel_preview/default_with_count.html.erb
  test/components/previews/pathogen_tabs_panel_preview/underline.html.erb
  test/components/previews/pathogen_tabs_panel_preview/underline_with_count.html.erb
Labels: ready for review

#830 GraphQL: add queries for getting pipelines
  app/graphql/resolvers/pipeline_resolver.rb
  app/graphql/resolvers/pipelines_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/pipeline_type.rb
  app/graphql/types/query_type.rb
  db/schema.rb
  test/graphql/pipeline_query_test.rb
  test/graphql/pipelines_query_test.rb
Labels: ready for review, graphql
