Repository phac-nml/irida-next, pull requests merged in 2024-07, with the labels that each got.

#638 Documentation for storage and extra ENV options
  .github/workflows/docs-site.yml
  config/storage.yml
  docs-site/docs/configuration/options.md
  docs-site/docs/configuration/storage.md
Labels: documentation

#628 Docs: Flesh out ga4gh wes docs
  docs-site/docs/configuration/ga4gh_wes.md
Labels: documentation, ready for review

#626 Docs: Workflow Executions
  docs-site/docs/user/analysis/_category_.json
  docs-site/docs/user/analysis/assets/rocket_launch.svg
  docs-site/docs/user/analysis/getting-started.md
  docs-site/docs/user/analysis/workflow-execution-types.md
  docs-site/docs/user/analysis/working-with-workflow-executions.md
  docs-site/docs/user/export/working-with-exports.md
Labels: documentation, ready for review

#672 Fix: Rendering files in samplesheet component (ENHC0010030)
  app/controllers/concerns/workflow_execution_actions.rb
  app/services/workflow_executions/preparation_service.rb
  app/views/workflow_executions/_samplesheet.html.erb
  lib/irida/pipeline.rb
  test/fixtures/workflow_executions.yml
Labels: ready for review

#665 [STRY0011998] Linelist Export Service and Job
  Gemfile
  Gemfile.lock
  app/controllers/data_exports_controller.rb
  app/controllers/groups/samples_controller.rb
  app/graphql/resolvers/samples_resolver.rb
  app/jobs/data_exports/create_job.rb
  app/models/data_export.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/policies/sample_policy.rb
  app/services/data_exports/create_service.rb
  app/views/data_exports/_new_sample_export_dialog.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  db/seeds.rb
  test/controllers/data_exports_controller_test.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/data_exports.yml
  test/fixtures/files/data_export_8.csv
  test/fixtures/files/data_export_9.xlsx
  test/jobs/data_exports/create_job_test.rb
  test/models/data_export_test.rb
  test/policies/sample_policy_test.rb
  test/services/data_exports/create_service_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#673 Groups: share groups and projects tab on details page
  app/controllers/groups/shared_namespaces_controller.rb
  app/models/group.rb
  app/views/groups/shared_namespaces/index.turbo_stream.erb
  app/views/groups/shared_projects/index.turbo_stream.erb
  app/views/groups/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/group.rb
  test/components/previews/viral_empty_component_preview/default.html.erb
  test/components/viral/empty_component_test.rb
  test/controllers/groups/shared_namespaces_controller_test.rb
  test/system/groups_test.rb
Labels: ready for review

#674 [STRY0011998] Linelist Exports: Controller
  app/controllers/data_exports_controller.rb
  test/controllers/data_exports_controller_test.rb
Labels: ready for review

#675 GraphQL: Add timestamps
  app/graphql/irida_schema.rb
  app/graphql/schema.graphql
  app/graphql/types/attachment_type.rb
  app/graphql/types/base_type.rb
  app/graphql/types/namespace_type.rb
  app/graphql/types/project_type.rb
  app/graphql/types/sample_type.rb
  app/graphql/types/user_type.rb
  test/graphql/attachments_query_test.rb
  test/graphql/group_query_test.rb
  test/graphql/groups_query_test.rb
  test/graphql/namespace_query_test.rb
  test/graphql/project_query_test.rb
  test/graphql/sample_query_test.rb
Labels: ready for review, graphql

#656 [ENHC0010038] Components/groups search and sort
  app/components/groups/table_component.en.yml
  app/components/groups/table_component.fr.yml
  app/components/groups/table_component.html.erb
  app/components/groups/table_component.rb
  app/controllers/concerns/share_actions.rb
  app/models/member.rb
  app/models/namespace_group_link.rb
  app/views/groups/group_links/_invited_groups.html.erb
  app/views/groups/group_links/create.turbo_stream.erb
  app/views/groups/group_links/destroy.turbo_stream.erb
  app/views/groups/group_links/index.turbo_stream.erb
  app/views/groups/members/index.html.erb
  app/views/projects/group_links/_invited_groups.html.erb
  app/views/projects/group_links/create.turbo_stream.erb
  app/views/projects/group_links/destroy.turbo_stream.erb
  app/views/projects/group_links/index.turbo_stream.erb
  app/views/projects/members/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/groups/table_component_test.rb
  test/system/groups/group_links_test.rb
  test/system/projects/group_links_test.rb
Labels: enhancement, ready for review
