Repository phac-nml/irida-next, pull requests merged in 2024-03, with the labels that each got.

#454 Fix: Sample sheet rendering to nextflow submission form
  app/components/nextflow/samplesheet_component.html.erb
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  test/system/workflow_executions/submissions_test.rb
Labels: bug, ready for review

#443 Workflow Executions: Workflow schema read from workflow
  app/components/nextflow/samplesheet/sample_cell_component.html.erb
  app/components/nextflow_component.html.erb
  app/components/nextflow_component.rb
  app/controllers/workflow_executions/submissions_controller.rb
  app/services/workflow_executions/preparation_service.rb
  app/views/workflow_executions/submissions/new.turbo_stream.erb
  test/components/nextflow_component_test.rb
  test/components/nextflow_samplesheet_component_test.rb
  test/fixtures/workflow_executions.yml
  test/services/workflow_executions/create_service_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement, ready for review

#440 Project Samples: Filter by name or puid list
  app/assets/icons/heroicons/document_magnifying_glass.svg
  app/components/viral/dialog/header_component.html.erb
  app/components/viral/dialog/header_component.rb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  app/components/viral/pill_component.html.erb
  app/javascript/controllers/filter_list_controller.js
  app/javascript/controllers/selection_controller.js
  app/javascript/controllers/viral/dialog_controller.js
  app/views/projects/samples/_tagged_filter.html.erb
  app/views/projects/samples/index.html.erb
  config/locales/en.yml
  test/components/previews/viral_dialog_component_preview.rb
  test/components/previews/viral_dialog_component_preview/non_closable.html.erb
  test/components/previews/viral_pill_component_preview.rb
  test/components/previews/viral_pill_component_preview/with_content.html.erb
  test/components/viral/dialog_component_test.rb
  test/components/viral/pill_component_test.rb
  test/components/viral/system/dialog_component_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#452 Migrate primary IDs to UUIDs
  app/components/history_version_component.html.erb
  app/javascript/controllers/projects/samples/attachments/selected_attachments_controller.js
  app/javascript/controllers/transfer_controller.js
  app/models/application_record.rb
  app/models/namespace.rb
  app/services/samples/clone_service.rb
  app/services/samples/transfer_service.rb
  config/importmap.rb
  db/migrate/20240229165646_migrate_to_uuid.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/attachments.yml
  test/fixtures/data_exports.yml
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespace_group_links.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/personal_access_tokens.yml
  test/fixtures/projects.yml
  test/fixtures/samples.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/models/members/group_member_test.rb
  test/models/members/project_member_test.rb
  test/system/groups/samples_test.rb
  test/system/profile_test.rb
Labels: ready for review

#460 Fix: filter by name removing last character
  app/javascript/controllers/filter_list_controller.js
  test/system/projects/samples_test.rb
Labels: bug

#438 Documentation: Pipeline Configuration
  docs-site/docs/configuration/pipelines.md
Labels: documentation, ready for review

#444 Data Export - Create Service
  app/models/member.rb
  app/policies/project_policy.rb
  app/services/data_exports/create_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/data_exports/create_service_test.rb
Labels: ready for review

#446 Data Export - Destroy Service
  app/models/data_export.rb
  app/policies/data_export_policy.rb
  app/services/data_exports/destroy_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240313142828_remove_deleted_at_from_data_exports.rb
  db/schema.rb
  test/models/data_export_test.rb
  test/services/data_exports/destroy_service_test.rb
Labels: ready for review

#462 Sample files updated column
  app/models/attachment.rb
  app/models/sample.rb
  app/views/groups/samples/_table.html.erb
  app/views/projects/samples/_table.html.erb
  config/locales/en.yml
  db/migrate/20240311152411_add_attachments_updated_at_to_samples.rb
  db/migrate/20240311152839_modify_sample_logidze_trigger_v03.rb
  db/migrate/20240311204201_add_attachments_updated_at_to_workflow_executions.rb
  db/migrate/20240311204219_add_attachments_updated_at_to_samples_workflow_executions.rb
  db/schema.rb
  db/triggers/logidze_on_samples_v03.sql
  test/fixtures/samples.yml
  test/models/sample_test.rb
  test/services/attachments/concatenation_service_test.rb
  test/services/attachments/create_service_test.rb
  test/services/attachments/destroy_service_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, database, ready for review

#456 Project Samples: Select all
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/filters_controller.js
  app/javascript/controllers/selection_controller.js
  app/javascript/controllers/table_selection_controller.js
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/select.turbo_stream.erb
  config/locales/en.yml
  config/routes/project.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#477 Fix submissions test
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  config/initializers/pipelines.rb
  lib/irida/pipelines.rb
  test/lib/irida/pipelines_test.rb
  test/system/workflow_executions/submissions_test.rb
  tmp/storage/.keep
Labels: ready for review

#481 Data Export - Controller
  app/controllers/data_exports_controller.rb
  app/policies/data_export_policy.rb
  config/routes.rb
  test/controllers/data_exports_controller_test.rb
Labels: ready for review

#482 Fix: nextflow component and nextflow samplesheet component preview
  test/components/previews/nextflow_component_preview.rb
  test/components/previews/nextflow_component_preview/default.html.erb
  test/components/previews/nextflow_samplesheet_component_preview.rb
Labels: bug

#439 Workflow: Completion Service
  app/models/workflow_execution.rb
  app/services/workflow_executions/completion_service.rb
  app/services/workflow_executions/preparation_service.rb
  db/migrate/20240320201313_add_blob_run_dir_to_workflow_execution.rb
  db/schema.rb
  test/active_storage_test_case.rb
  test/fixtures/files/blob_outputs/no_files/iridanext.output.json.gz
  test/fixtures/files/blob_outputs/normal/iridanext.output.json.gz
  test/fixtures/files/blob_outputs/normal/summary.txt
  test/fixtures/workflow_executions.yml
  test/services/workflow_executions/completion_service_test.rb
  test/services/workflow_executions/preparation_service_test.rb
  test/test_helpers/blob_helpers.rb
Labels: enhancement, database, ready for review

#449 Data Export - Create Job
  Gemfile
  Gemfile.lock
  app/helpers/business_days_helper.rb
  app/jobs/data_exports/create_job.rb
  app/services/data_exports/create_service.rb
  config/business_time.yml
  config/initializers/business_time.rb
  test/fixtures/data_exports.yml
  test/helpers/business_days_helper_test.rb
  test/jobs/data_exports/create_job_test.rb
Labels: ready for review

#479 Prefix workflow submission inputs
  app/components/viral/form/prefixed/boolean_component.html.erb
  app/components/viral/form/prefixed/boolean_component.rb
  app/components/viral/form/prefixed/select_component.html.erb
  app/components/viral/form/prefixed/select_component.rb
  app/components/viral/form/prefixed/text_input_component.html.erb
  app/components/viral/form/prefixed/text_input_component.rb
  app/components/viral/form/text_input_component.html.erb
  app/helpers/nextflow_helper.rb
  app/helpers/view_helper.rb
  test/components/previews/viral_form_prefixed_boolean_component_preview.rb
  test/components/previews/viral_form_prefixed_boolean_component_preview/default.html.erb
  test/components/previews/viral_form_prefixed_boolean_component_preview/with_false_value.html.erb
  test/components/previews/viral_form_prefixed_boolean_component_preview/with_icon.html.erb
  test/components/previews/viral_form_prefixed_select_component_preview.rb
  test/components/previews/viral_form_prefixed_select_component_preview/default.html.erb
  test/components/previews/viral_form_prefixed_select_component_preview/with_icon.html.erb
  test/components/previews/viral_form_prefixed_text_input_component_preview.rb
  test/components/previews/viral_form_prefixed_text_input_component_preview/default.html.erb
  test/components/previews/viral_form_prefixed_text_input_component_preview/with_icon.html.erb
  test/components/viral/form/prefixed/boolean_component_test.rb
  test/components/viral/form/prefixed/select_component_test.rb
  test/components/viral/form/prefixed/text_input_component_test.rb
Labels: enhancement

#493 Fix Paired Files Export Test
  test/fixtures/data_exports.yml
  test/jobs/data_exports/create_job_test.rb
Labels: ready for review

#489 Seed Exports
  db/seeds.rb
Labels: ready for review

#483 Data Export - Listing
  app/assets/icons/heroicons/arrow_up_on_square_stack.svg
  app/components/layout/sidebar_component.html.erb
  app/controllers/data_exports_controller.rb
  app/views/data_exports/_table.html.erb
  app/views/data_exports/destroy.turbo_stream.erb
  app/views/data_exports/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/data_exports_controller_test.rb
  test/fixtures/data_exports.yml
  test/system/data_exports_test.rb
Labels: ready for review

#487 Workflow: Completion Service sample data / metadata
  app/helpers/blob_helper.rb
  app/models/samples_workflow_execution.rb
  app/services/workflow_executions/completion_service.rb
  db/migrate/20240322161330_add_metadata_to_samples_workflow_executions.rb
  db/schema.rb
  test/active_storage_test_case.rb
  test/fixtures/files/blob_outputs/missing_entry/analysis3.txt
  test/fixtures/files/blob_outputs/missing_entry/iridanext.output.json
  test/fixtures/files/blob_outputs/missing_entry/summary.txt
  test/fixtures/files/blob_outputs/no_files/iridanext.output.json
  test/fixtures/files/blob_outputs/no_files/iridanext.output.json.gz
  test/fixtures/files/blob_outputs/normal/iridanext.output.json
  test/fixtures/files/blob_outputs/normal/iridanext.output.json.gz
  test/fixtures/files/blob_outputs/normal2/analysis1.txt
  test/fixtures/files/blob_outputs/normal2/analysis2.txt
  test/fixtures/files/blob_outputs/normal2/analysis3.txt
  test/fixtures/files/blob_outputs/normal2/iridanext.output.json
  test/fixtures/files/blob_outputs/normal2/summary.txt
  test/fixtures/samples.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/services/workflow_executions/completion_service_test.rb
  test/test_helpers/blob_helpers.rb
  test/test_helpers/blob_test_helpers.rb
Labels: enhancement, database, ready for review
