Repository phac-nml/irida-next, pull requests merged in 2024-02, with the labels that each got.

#387 Edit metadata
  app/controllers/projects/samples/attachments/concatenations_controller.rb
  app/controllers/projects/samples/attachments/deletions_controller.rb
  app/controllers/projects/samples/attachments_controller.rb
  app/controllers/projects/samples/metadata/fields_controller.rb
  app/controllers/projects/samples/metadata_controller.rb
  app/models/sample.rb
  app/services/samples/metadata/fields/update_service.rb
  app/views/projects/samples/attachments/concatenations/create.turbo_stream.erb
  app/views/projects/samples/attachments/create.turbo_stream.erb
  app/views/projects/samples/attachments/deletions/destroy.turbo_stream.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/projects/samples/metadata/_update_form.html.erb
  app/views/projects/samples/metadata/_update_metadata_modal.html.erb
  app/views/projects/samples/metadata/fields/update.turbo_stream.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples/metadata/fields/fields_controller_test.rb
  test/controllers/projects/samples/metadata_controller_test.rb
  test/fixtures/members.yml
  test/models/sample_test.rb
  test/services/samples/metadata/fields/update_service_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#411 Fixed issue with import metadata modal hijacking the dialog on project samples page
  app/javascript/controllers/projects/samples/metadata/file_import_controller.js
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/metadata/file_imports/new.turbo_stream.erb
  test/system/projects/samples_test.rb
Labels: ready for review

#395 Project history view
  Gemfile.lock
  app/assets/icons/heroicons/list_bullet.svg
  app/assets/stylesheets/application.tailwind.css
  app/components/history_component.html.erb
  app/components/history_component.rb
  app/components/history_version_component.html.erb
  app/components/history_version_component.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/history_actions.rb
  app/controllers/projects/history_controller.rb
  app/controllers/projects_controller.rb
  app/helpers/json_helper.rb
  app/helpers/path_helper.rb
  app/javascript/controllers/collapsible_controller.js
  app/models/concerns/history.rb
  app/models/member.rb
  app/models/namespaces/project_namespace.rb
  app/policies/project_policy.rb
  app/views/layouts/projects.html.erb
  app/views/projects/history/_project_history_modal.html.erb
  app/views/projects/history/_project_history_modal_description.html.erb
  app/views/projects/history/index.html.erb
  app/views/projects/history/index.turbo_stream.erb
  app/views/projects/history/new.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  db/migrate/20240205175935_modify_namespace_logidze_trigger.rb
  db/schema.rb
  db/seeds.rb
  db/triggers/logidze_on_namespaces_v02.sql
  test/components/history_component_test.rb
  test/components/history_version_component_test.rb
  test/components/previews/history_component_preview.rb
  test/components/previews/history_component_preview/default.html.erb
  test/components/previews/history_version_component_preview.rb
  test/components/previews/history_version_component_preview/default.html.erb
  test/components/previews/viral_dialog_component_preview/confirmation.html.erb
  test/controllers/concerns/history_actions_concern_test.rb
  test/controllers/projects/history_controller_test.rb
  test/models/concerns/history_concern_test.rb
  test/system/projects/history_test.rb
Labels: ready for review

#374 Workflow Executions: Cancel
  Gemfile.lock
  app/controllers/workflow_executions_controller.rb
  app/jobs/workflow_execution_cancelation_job.rb
  app/jobs/workflow_execution_preparation_job.rb
  app/jobs/workflow_execution_submission_job.rb
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancel_service.rb
  app/views/workflow_executions/_workflow_execution.html.erb
  app/views/workflow_executions/cancel.turbo_stream.erb
  app/views/workflow_executions/index.html.erb
  config/locales/en.yml
  config/routes/workflow_executions.rb
  test/controllers/workflow_executions_controller_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#380 Add metadata
  app/assets/stylesheets/application.tailwind.css
  app/controllers/projects/samples/metadata/fields_controller.rb
  app/controllers/projects/samples/metadata_controller.rb
  app/javascript/controllers/projects/samples/metadata/create_controller.js
  app/services/samples/metadata/fields/create_service.rb
  app/views/projects/samples/metadata/_form.html.erb
  app/views/projects/samples/metadata/_new_metadata_modal.html.erb
  app/views/projects/samples/metadata/fields/create.turbo_stream.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples/metadata/fields/fields_controller_test.rb
  test/services/samples/metadata/fields/create_service_test.rb
  test/services/samples/metadata/fields/update_service_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#414 Refresh project sample table even on errors to make sure no data has changes
  app/javascript/controllers/projects/samples/metadata/complete_controller.js
  app/javascript/controllers/projects/samples/metadata/file_import_controller.js
  app/views/projects/samples/metadata/file_imports/_errors.html.erb
  app/views/projects/samples/metadata/file_imports/_success.html.erb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#392 Graphql attach files to sample mutation
  app/graphql/mutations/attach_files_to_sample.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  app/services/attachments/create_service.rb
  test/fixtures/active_storage/blobs.yml
  test/fixtures/files/afts.fastq
  test/fixtures/files/afts_b.fastq
  test/fixtures/files/md5_a
  test/fixtures/files/md5_b
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/personal_access_tokens.yml
  test/fixtures/projects.yml
  test/fixtures/samples.yml
  test/graphql/attach_files_to_sample_test.rb
Labels: ready for review, graphql

#410 GraphQL Documentation
  docs-site/README.md
  docs-site/docs/configuration/_category_.json
  docs-site/docs/development/_category_.json
  docs-site/docs/extend/_category_.json
  docs-site/docs/extend/graphql.md
Labels: documentation, ready for review, graphql

#421 Workflow: Fix select component
  app/helpers/nextflow_helper.rb
Labels: bug

#405 Delete metadata
  app/components/confirmation_component.html.erb
  app/controllers/projects/samples/metadata/deletions_controller.rb
  app/controllers/projects/samples/metadata_controller.rb
  app/javascript/controllers/projects/samples/attachments/selected_attachments_controller.js
  app/javascript/controllers/projects/samples/metadata/delete_listing_controller.js
  app/javascript/controllers/projects/samples/metadata/destroy_controller.js
  app/javascript/controllers/selection_controller.js
  app/services/samples/metadata/fields/update_service.rb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/samples/attachments/concatenations/_modal.html.erb
  app/views/projects/samples/attachments/deletions/_modal.html.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/projects/samples/metadata/deletions/_modal.html.erb
  app/views/projects/samples/metadata/deletions/destroy.turbo_stream.erb
  app/views/projects/samples/metadata/destroy.turbo_stream.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples/metadata/deletions_controller_test.rb
  test/controllers/projects/samples/metadata_controller_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#423 Fixed deleted metadata keys not displaying in version log
  app/components/history_version_component.html.erb
  config/locales/en.yml
  test/components/history_component_test.rb
  test/components/history_version_component_test.rb
Labels: bug

#418 Add puid to samples and projects
  app/components/viral/page_header_component.html.erb
  app/components/viral/page_header_component.rb
  app/components/viral/pill_component.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/models/sample.rb
  app/views/groups/samples/_table.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/show.html.erb
  app/views/projects/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/viral/pill_component_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#417 Workflow submission file selection
  app/components/nextflow/samplesheet/dropdown_cell_component.html.erb
  app/components/nextflow/samplesheet/dropdown_cell_component.rb
  app/components/nextflow/samplesheet/row_component.html.erb
  app/components/nextflow/samplesheet/row_component.rb
  app/components/nextflow/samplesheet/sample_cell_component.html.erb
  app/components/nextflow/samplesheet/text_cell_component.rb
  app/components/nextflow/samplesheet_component.en.yml
  app/components/nextflow/samplesheet_component.fr.yml
  app/components/nextflow/samplesheet_component.html.erb
  app/components/nextflow/samplesheet_component.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  test/components/nextflow_samplesheet_component_test.rb
  test/components/previews/nextflow_component_preview.rb
Labels: enhancement, ready for review

#408 GraphQL: Attachment Type
  app/graphql/resolvers/attachment_metadata_resolver.rb
  app/graphql/resolvers/sample_attachments_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/attachment_type.rb
  app/graphql/types/sample_type.rb
  app/models/attachment.rb
  test/graphql/attachments_query_test.rb
Labels: enhancement, ready for review, graphql

#442 Workflow Execution: Fixed workflow checkboxes
  app/components/viral/form/checkbox_component.html.erb
  app/helpers/nextflow_helper.rb
  test/components/previews/nextflow_component_preview/default.html.erb
Labels: bug, ready for review
