Repository phac-nml/irida-next, pull requests merged in 2024-08, with the labels that each got.

#677 Attachments: File format detection
  app/components/viral/pill_component.rb
  app/helpers/pill_color_helper.rb
  app/models/attachment.rb
  test/fixtures/files/metadata/valid.csv.gz
  test/fixtures/files/metadata/valid.tsv.gz
  test/fixtures/files/sequence.gbf
  test/fixtures/files/sequence.gbf.gz
  test/fixtures/files/sequence.gbk
  test/fixtures/files/sequence.gbk.gz
  test/fixtures/files/sequence.genbank
  test/fixtures/files/sequence.genbank.gz
  test/fixtures/files/test_file_15.txt.gz
  test/fixtures/files/test_file_16.rtf.gz
  test/fixtures/files/test_file_17.json
  test/fixtures/files/test_file_18.json.gz
  test/models/attachment_test.rb
Labels: enhancement, ready for review

#679 Samples table enhancements
  Gemfile.lock
  app/components/list_filter_component.html.erb
  app/components/pagination_component.html.erb
  app/components/pagination_component.rb
  app/components/ransack/sort_component.html.erb
  app/components/ransack/sort_component.rb
  app/components/samples/table_component.en.yml
  app/components/samples/table_component.fr.yml
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples/deletions_controller.rb
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/action_link_controller.js
  app/javascript/controllers/list_filter_controller.js
  app/javascript/controllers/selection_controller.js
  app/views/groups/samples/index.html.erb
  app/views/groups/samples/index.turbo_stream.erb
  app/views/layouts/partials/_head.html.erb
  app/views/projects/samples/clones/create.turbo_stream.erb
  app/views/projects/samples/deletions/_new_deletion_dialog.html.erb
  app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb
  app/views/projects/samples/deletions/destroy.turbo_stream.erb
  app/views/projects/samples/deletions/destroy_multiple.turbo_stream.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/index.turbo_stream.erb
  app/views/projects/samples/metadata/deletions/_modal.html.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  test/controllers/projects/samples/deletions_controller_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#682 Sample Exports: Backend - Attachment Format Filtering
  app/controllers/data_exports_controller.rb
  app/jobs/data_exports/create_job.rb
  app/models/data_export.rb
  config/locales/en.yml
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/data_exports.yml
  test/fixtures/samples.yml
  test/jobs/data_exports/create_job_test.rb
  test/models/data_export_test.rb
  test/services/data_exports/create_service_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#686 Local time
  Gemfile
  Gemfile.lock
  app/components/groups/table_component.html.erb
  app/components/history_component.html.erb
  app/components/members/table_component.html.erb
  app/components/samples/table_component.html.erb
  app/components/updated_component.html.erb
  app/components/updated_component.rb
  app/components/viral/time_ago_component.html.erb
  app/components/viral/time_ago_component.rb
  app/helpers/view_helper.rb
  app/javascript/application.js
  app/views/data_exports/_data_export.html.erb
  app/views/data_exports/_summary.html.erb
  app/views/groups/bots/_bot.html.erb
  app/views/groups/bots/personal_access_tokens/_personal_access_token.html.erb
  app/views/groups/group_links/_namespace_group_link.html.erb
  app/views/groups/group_links/update.turbo_stream.erb
  app/views/groups/members/update.turbo_stream.erb
  app/views/mailers/data_export_mailer/export_ready.html.erb
  app/views/profiles/personal_access_tokens/_personal_access_token.html.erb
  app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
  app/views/projects/bots/_bot.html.erb
  app/views/projects/bots/personal_access_tokens/_personal_access_token.html.erb
  app/views/projects/group_links/_namespace_group_link.html.erb
  app/views/projects/group_links/update.turbo_stream.erb
  app/views/projects/members/update.turbo_stream.erb
  app/views/projects/samples/attachments/_attachment.html.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/projects/workflow_executions/_attachment.html.erb
  app/views/projects/workflow_executions/_summary.html.erb
  app/views/projects/workflow_executions/_workflow_execution.html.erb
  app/views/shared/project/_row.html.erb
  app/views/workflow_executions/_attachment.html.erb
  app/views/workflow_executions/_summary.html.erb
  app/views/workflow_executions/_workflow_execution.html.erb
  config/importmap.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/updated_component_preview.rb
  test/components/previews/updated_component_preview/default.html.erb
  test/components/previews/viral_time_ago_component_preview/current_time_input.html.erb
  test/components/previews/viral_time_ago_component_preview/default.html.erb
  test/components/updated_component_test.rb
  test/components/viral/system/time_ago_component_test.rb
  test/system/groups/group_links_test.rb
  test/system/groups/members_test.rb
  test/system/projects/group_links_test.rb
  test/system/projects/members_test.rb
  vendor/javascript/local-time.js
Labels: ready for review

#690 Sample Exports: Format Filtering UI
  app/components/viral/sortable_list/list_component.html.erb
  app/components/viral/sortable_lists_component.html.erb
  app/controllers/data_exports_controller.rb
  app/javascript/controllers/infinite_scroll_controller.js
  app/javascript/controllers/viral/sortable_lists/list_controller.js
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/jobs/data_exports/create_job.rb
  app/models/data_export.rb
  app/views/data_exports/_new_linelist_export_dialog.html.erb
  app/views/data_exports/_new_sample_export_dialog.html.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/data_exports_controller_test.rb
  test/fixtures/data_exports.yml
  test/models/data_export_test.rb
  test/services/data_exports/create_service_test.rb
  test/system/data_exports_test.rb
  test/system/groups/group_links_test.rb
  test/system/projects/group_links_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#699 Enhancement: Attachment Checksum Validation
  app/validators/attachment_checksum_validator.rb
  test/graphql/attach_files_to_sample_test.rb
  test/models/attachment_test.rb
  test/system/data_exports_test.rb
Labels: enhancement

#707 Analysis Exports: Backend - Accept multiple workflow IDs
  app/controllers/data_exports_controller.rb
  app/jobs/data_exports/create_job.rb
  app/models/data_export.rb
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/policies/project_policy.rb
  app/policies/workflow_execution_policy.rb
  app/services/data_exports/create_service.rb
  app/views/data_exports/_new_analysis_export_dialog.html.erb
  app/views/groups/samples/_table.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/workflow_executions/show.html.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/data_exports_controller_test.rb
  test/fixtures/data_exports.yml
  test/jobs/data_exports/create_job_test.rb
  test/models/data_export_test.rb
  test/policies/project_policy_test.rb
  test/services/data_exports/create_service_test.rb
Labels: ready for review

#693 Enhancement: Samples table pagination and page size
  Gemfile
  Gemfile.lock
  app/components/pagination_component.html.erb
  app/components/samples/table_component.en.yml
  app/components/samples/table_component.fr.yml
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  app/components/viral/pagy/limit_component.en.yml
  app/components/viral/pagy/limit_component.fr.yml
  app/components/viral/pagy/limit_component.html.erb
  app/components/viral/pagy/limit_component.rb
  app/components/viral/pagy/pagination_component.en.yml
  app/components/viral/pagy/pagination_component.fr.yml
  app/components/viral/pagy/pagination_component.html.erb
  app/components/viral/pagy/pagination_component.rb
  config/initializers/pagy.rb
  test/system/data_exports_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement

#721 Fixed dark mode issues with Pagy Pagination Component
  app/components/viral/pagy/pagination_component.html.erb
  app/components/viral/pagy/pagination_component.rb
  test/components/previews/viral_pagy_limit_component_preview.rb
  test/components/previews/viral_pagy_pagination_component_preview.rb
  test/components/viral/pagy_limit_component_preview_test.rb
  test/components/viral/pagy_pagination_component_preview_test.rb
  test/system/groups/samples_test.rb
Labels: enhancement

#718 Enhancement: Export Show
  app/controllers/data_exports_controller.rb
  app/models/data_export.rb
  app/views/data_exports/show.html.erb
  app/views/data_exports/show.turbo_stream.erb
  test/system/data_exports_test.rb
Labels: enhancement, ready for review

#724 Enhancement: Data Export Index
  app/controllers/data_exports_controller.rb
  app/models/data_export.rb
  app/services/data_exports/create_service.rb
  app/views/data_exports/destroy.turbo_stream.erb
  app/views/data_exports/index.html.erb
  app/views/data_exports/show.html.erb
  test/controllers/data_exports_controller_test.rb
  test/jobs/data_exports/create_job_test.rb
  test/models/data_export_test.rb
Labels: enhancement, ready for review
