Repository phac-nml/irida-next, pull requests merged in 2024-10, with the labels that each got.

#788 Namespace Attachments: Empty Search State
  app/components/attachments/dialogs/delete_attachment_component.html.erb
  app/components/attachments/table_component.html.erb
  app/components/attachments/table_component.rb
  app/controllers/concerns/attachment_actions.rb
  app/views/groups/attachments/_table.html.erb
  app/views/groups/attachments/index.html.erb
  app/views/projects/attachments/_table.html.erb
  app/views/projects/attachments/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
Labels: ready for review

#799 GraphQL: CreateGroup mutation
  app/graphql/mutations/create_group.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  test/graphql/create_group_mutation_test.rb
Labels: ready for review, graphql

#802 feat: Added cancel button to filter by name or puid
  app/assets/stylesheets/application.tailwind.css
  app/components/list_filter_component.html.erb
  app/components/viral/dialog_component.html.erb
  app/javascript/controllers/list_filter_controller.js
  config/locales/fr.yml
  test/system/projects/samples_test.rb
Labels: enhancement

#798 Fix: Sample selection refresh
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/select.turbo_stream.erb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/graphql/groups_query_ransack_test.rb
  test/policies/group_policy_test.rb
  test/policies/namespace_policy_test.rb
  test/policies/project_policy_test.rb
  test/system/dashboard/projects_test.rb
  test/system/projects/samples_test.rb
Labels: bug

#804 Fix upload dialog upload button for groups/project not disabling when uploading
  app/components/attachments/dialogs/new_attachment_component.html.erb
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
  test/system/projects/samples_test.rb
Labels: bug, ready for review

#797 Docs: Update Metadata Import
  docs-site/docs/user/project/samples/sample-metadata.md
Labels: documentation

#805 Submit search on enter
  app/components/list_filter_component.html.erb
  app/components/ransack/hidden_sort_field_component.rb
  app/components/search_component.html.erb
  app/components/search_component.rb
  app/components/viral/tabs_component.html.erb
  app/components/viral/tabs_component.rb
  app/javascript/controllers/filters_controller.js
  app/javascript/controllers/selection_controller.js
  app/views/dashboard/groups/index.html.erb
  app/views/dashboard/projects/index.html.erb
  app/views/dashboard/projects/index.turbo_stream.erb
  app/views/data_exports/index.html.erb
  app/views/groups/attachments/index.html.erb
  app/views/groups/group_links/_invited_groups.html.erb
  app/views/groups/members/_member_listing.html.erb
  app/views/groups/members/index.html.erb
  app/views/groups/samples/index.html.erb
  app/views/groups/show.html.erb
  app/views/projects/attachments/index.html.erb
  app/views/projects/members/index.html.erb
  app/views/projects/samples/index.html.erb
  test/components/members/search_component_test.rb
  test/components/previews/search_component_preview/default.html.erb
  test/components/viral/system/list_filter_component_test.rb
  test/system/dashboard/groups_test.rb
  test/system/dashboard/projects_test.rb
  test/system/data_exports_test.rb
  test/system/groups/attachments_test.rb
  test/system/groups/group_links_test.rb
  test/system/groups/members_test.rb
  test/system/groups/samples_test.rb
  test/system/groups_test.rb
  test/system/projects/attachments_test.rb
  test/system/projects/group_links_test.rb
  test/system/projects/members_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#817 Analysis Exports: Error when including non-completed workflow executions
  app/controllers/data_exports_controller.rb
  app/services/data_exports/create_service.rb
  app/views/data_exports/create.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/data_exports/create_service_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#827 Fix: Render flat list for groups when filtering
  app/controllers/dashboard/groups_controller.rb
  app/controllers/groups_controller.rb
  app/views/groups/subgroups/_index.html.erb
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
Labels: ready for review

#824 Updated highlighting on project and groups samples pages when search by name or puid AND a metadata field
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/views/groups/samples/_table.html.erb
  app/views/projects/samples/_table.html.erb
Labels: enhancement, ready for review

#783 Groups/samples_count
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/namespace_tree/row/row_contents_component.rb
  app/components/namespace_tree/row/without_children_component.html.erb
  app/models/group.rb
  app/services/groups/destroy_service.rb
  app/services/groups/transfer_service.rb
  app/services/projects/destroy_service.rb
  app/services/projects/transfer_service.rb
  app/services/samples/clone_service.rb
  app/services/samples/create_service.rb
  app/services/samples/destroy_service.rb
  app/services/samples/transfer_service.rb
  db/migrate/20240925230422_add_samples_count_to_namespaces.rb
  db/migrate/20241004162923_reset_all_group_samples_counters.rb
  db/schema.rb
  test/fixtures/groups.yml
  test/fixtures/projects.yml
  test/models/group_test.rb
  test/models/project_test.rb
  test/services/groups/destroy_service_test.rb
  test/services/groups/transfer_service_test.rb
  test/services/projects/destroy_service_test.rb
  test/services/projects/transfer_service_test.rb
  test/services/samples/clone_service_test.rb
  test/services/samples/create_service_test.rb
  test/services/samples/destroy_service_test.rb
  test/services/samples/transfer_service_test.rb
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
Labels: ready for review

#822 Prettier updates
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  babel.config.js
  package.json
  pnpm-lock.yaml
  prettier.config.js
Labels: ready for review, dependencies
