Repository phac-nml/irida-next, pull requests merged in 2024-04, with the labels that each got.

#499 Namespace PUID
  app/graphql/mutations/create_sample.rb
  app/graphql/resolvers/group_resolver.rb
  app/graphql/resolvers/namespace_resolver.rb
  app/graphql/resolvers/project_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/namespace_type.rb
  app/models/concerns/history.rb
  app/models/group.rb
  app/models/namespace.rb
  app/models/namespaces/project_namespace.rb
  app/models/namespaces/user_namespace.rb
  app/models/project.rb
  app/views/groups/show.html.erb
  db/migrate/20240325190420_add_puid_to_namespace.rb
  db/schema.rb
  test/fixtures/groups.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/projects.yml
  test/graphql/group_query_test.rb
  test/models/group_test.rb
  test/models/namespace_test.rb
  test/models/namespaces/project_namespace_test.rb
  test/models/project_test.rb
Labels: database, ready for review

#504 Workflow executions: Handle metadata and attachments
  app/helpers/metadata_helper.rb
  app/services/workflow_executions/completion_service.rb
  test/fixtures/files/blob_outputs/normal3/analysis1.txt
  test/fixtures/files/blob_outputs/normal3/analysis2.txt
  test/fixtures/files/blob_outputs/normal3/analysis3.txt
  test/fixtures/files/blob_outputs/normal3/iridanext.output.json
  test/fixtures/files/blob_outputs/normal3/summary.txt
  test/fixtures/projects.yml
  test/fixtures/samples.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/helpers/metadata_helper_test.rb
  test/services/workflow_executions/completion_service_test.rb
Labels: enhancement, ready for review

#490 Data Export - Individual Listing Page
  app/assets/icons/heroicons/folder_open.svg
  app/controllers/data_exports_controller.rb
  app/jobs/data_exports/create_job.rb
  app/policies/data_export_policy.rb
  app/views/data_exports/_preview.html.erb
  app/views/data_exports/_summary.html.erb
  app/views/data_exports/_table.html.erb
  app/views/data_exports/show.html.erb
  app/views/data_exports/show.turbo_stream.erb
  app/views/shared/loading/_list.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20240322161334_add_manifest_to_data_export.rb
  db/schema.rb
  test/controllers/data_exports_controller_test.rb
  test/fixtures/data_exports.yml
  test/jobs/data_exports/create_job_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#420 Authentication: External Sign In Label Customization
  .gitignore
  app/helpers/view_helper.rb
  app/views/devise/sessions/new_with_providers.html.erb
  config/application.rb
  config/authentication/auth_config.yml
  config/authentication/icons/.keep
  config/initializers/devise.rb
  docs-site/docs/configuration/authentication.md
  docs-site/docs/configuration/ga4gh_wes.md
  test/fixtures/files/tyrell.svg
  test/helpers/view_helper_test.rb
  test/system/sign_in_display_test.rb
Labels: documentation, enhancement, ready for review

#517 add custom text to signin success/failure popup
  app/controllers/users/omniauth_callbacks_controller.rb
Labels: enhancement, ready for review

#503 Data Export - Create Export UI
  app/controllers/data_exports_controller.rb
  app/javascript/controllers/data_export_controller.js
  app/policies/group_policy.rb
  app/services/data_exports/create_service.rb
  app/views/data_exports/_new_export_dialog.html.erb
  app/views/data_exports/create.turbo_stream.erb
  app/views/data_exports/index.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/data_exports_controller_test.rb
  test/fixtures/data_exports.yml
  test/jobs/data_exports/create_job_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#502 Workflow Submission: Sample Metadata
  app/components/nextflow/samplesheet/metadata_cell_component.html.erb
  app/components/nextflow/samplesheet/metadata_cell_component.rb
  app/components/nextflow/samplesheet/row_component.rb
  app/components/nextflow/samplesheet/sample_cell_component.html.erb
  app/components/nextflow/samplesheet_component.html.erb
  db/seeds.rb
  test/components/nextflow_samplesheet_component_test.rb
  test/fixtures/files/nextflow/samplesheet_schema_meta.json
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/policies/group_policy_test.rb
  test/policies/namespace_policy_test.rb
  test/policies/project_policy_test.rb
  test/system/dashboard/projects_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement

#528 FIX: Fixed auto selection of fastq_2
  app/javascript/controllers/nextflow/samplesheet_controller.js
Labels: bug, ready for review

#529 Multi level menu component
  app/components/layout/sidebar/multi_level_menu_component.html.erb
  app/components/layout/sidebar/multi_level_menu_component.rb
  app/components/layout/sidebar/section_component.html.erb
  app/components/layout/sidebar/section_component.rb
  app/components/layout/sidebar_component.html.erb
  test/components/layout/sidebar_component_test.rb
  test/components/previews/multi_level_menu_component_preview.rb
  test/components/previews/multi_level_menu_component_preview/default.html.erb
Labels: enhancement, ready for review

#531 Bot generate personal access token
  app/controllers/concerns/bot_actions.rb
  app/controllers/profiles/personal_access_tokens_controller.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/policies/user_policy.rb
  app/services/personal_access_tokens/create_service.rb
  app/views/projects/bots/generate_personal_access_token.turbo_stream.erb
  config/locales/en.yml
  config/routes/project.rb
  test/controllers/concerns/bot_actions_concern_test.rb
  test/controllers/projects/bots_controller_test.rb
  test/services/personal_access_tokens/create_service_test.rb
Labels: ready for review

#511 Fix: Select all JavaScript error when not available
  app/javascript/controllers/selection_controller.js
  app/views/projects/samples/_table.html.erb
Labels: bug, ready for review

#522 Fix cancel unsubmitted job error
  app/controllers/workflow_executions_controller.rb
  app/jobs/workflow_execution_status_job.rb
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancel_service.rb
  app/views/workflow_executions/cancel.turbo_stream.erb
  config/locales/en.yml
  test/controllers/workflow_executions_controller_test.rb
  test/system/workflow_executions_test.rb
Labels: bug, ready for review

#514 Data Export: Create Service - Add workflow execution
  app/policies/workflow_execution_policy.rb
  app/services/data_exports/create_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/data_exports/create_service_test.rb
Labels: ready for review

#540 FIX: Analyst workflow submission
  app/policies/project_policy.rb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespace_group_links.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/fixtures/users.yml
  test/policies/project_policy_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: bug

#534 Bot personal access token controller
  app/controllers/concerns/bot_actions.rb
  app/controllers/concerns/bot_personal_access_token_actions.rb
  app/controllers/projects/bots/personal_access_tokens_controller.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/services/bots/create_service.rb
  app/views/projects/bots/personal_access_tokens/create.turbo_stream.erb
  app/views/projects/bots/personal_access_tokens/index.turbo_stream.erb
  app/views/projects/bots/personal_access_tokens/new.turbo_stream.erb
  config/locales/en.yml
  config/routes/project.rb
  test/controllers/concerns/bot_actions_concern_test.rb
  test/controllers/concerns/bot_personal_access_token_actions_concern_test.rb
  test/controllers/projects/bots/personal_access_tokens_controller_test.rb
  test/controllers/projects/bots_controller_test.rb
Labels: ready for review

#535 Bot accounts UI
  app/assets/icons/heroicons/bug_ant.svg
  app/components/clipboard_component.html.erb
  app/components/layout/sidebar/multi_level_menu_component.html.erb
  app/controllers/concerns/bot_actions.rb
  app/views/layouts/projects.html.erb
  app/views/projects/bots/_access_token_section.html.erb
  app/views/projects/bots/_bot.html.erb
  app/views/projects/bots/_bot_listing.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/_pagination.html.erb
  app/views/projects/bots/create.turbo_stream.erb
  app/views/projects/bots/destroy.turbo_stream.erb
  app/views/projects/bots/index.html.erb
  app/views/projects/bots/index.turbo_stream.erb
  app/views/projects/bots/new.turbo_stream.erb
  app/views/projects/members/_member.html.erb
  config/locales/en.yml
  test/controllers/concerns/bot_actions_concern_test.rb
  test/controllers/concerns/bot_personal_access_token_actions_concern_test.rb
  test/controllers/groups/bots_controller_test.rb
  test/controllers/projects/bots/personal_access_tokens_controller_test.rb
  test/controllers/projects/bots_controller_test.rb
  test/fixtures/namespace_bots.yml
  test/fixtures/personal_access_tokens.yml
  test/fixtures/users.yml
  test/models/namespace_bot_test.rb
  test/services/bots/destroy_service_test.rb
  test/services/personal_access_tokens/create_service_test.rb
  test/system/projects/bots_test.rb
Labels: ready for review

#464 Data Export - Email Notification
  app/jobs/data_exports/create_job.rb
  app/mailers/data_export_mailer.rb
  app/mailers/pipeline_mailer.rb
  app/views/mailers/_email_template.html.erb
  app/views/mailers/data_export_mailer/export_ready.html.erb
  app/views/mailers/pipeline_mailer/complete_email.html.erb
  app/views/mailers/pipeline_mailer/error_email.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/mailers/data_export_mailer_test.rb
  test/mailers/pipeline_mailer_test.rb
  test/mailers/previews/data_export_mailer_preview.rb
Labels: ready for review

#526 Data Export: Add workflow execution to create job
  app/jobs/data_exports/create_job.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/data_exports.yml
  test/fixtures/files/INXT_SAM_AAAAAAAABV.assembly.fa.gz
  test/fixtures/files/summary.txt.gz
  test/fixtures/samples.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/jobs/data_exports/create_job_test.rb
  test/system/data_exports_test.rb
  test/system/workflow_executions_test.rb
Labels: ready for review

#532 Workflow Submission: Metadata field selection
  app/components/nextflow/samplesheet/dropdown_cell_component.html.erb
  app/components/nextflow/samplesheet/metadata_cell_component.html.erb
  app/components/nextflow/samplesheet/metadata_cell_component.rb
  app/components/nextflow/samplesheet/row_component.rb
  app/components/nextflow/samplesheet_component.en.yml
  app/components/nextflow/samplesheet_component.fr.yml
  app/components/nextflow/samplesheet_component.html.erb
  app/components/nextflow/samplesheet_component.rb
  app/components/nextflow_component.html.erb
  app/components/nextflow_component.rb
  app/controllers/workflow_executions/metadata_controller.rb
  app/controllers/workflow_executions/submissions_controller.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/javascript/controllers/sessionstorage_amend_form_controller.js
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  app/views/workflow_executions/metadata/fields.turbo_stream.erb
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  app/views/workflow_executions/submissions/create.turbo_stream.erb
  config/routes/workflow_executions.rb
  test/components/nextflow_component_test.rb
  test/components/nextflow_samplesheet_component_test.rb
  test/components/previews/nextflow_component_preview/default.html.erb
  test/components/previews/nextflow_samplesheet_component_preview.rb
  test/components/previews/nextflow_samplesheet_component_preview/default.html.erb
  test/fixtures/files/nextflow/samplesheet_schema_meta.json
  test/fixtures/samples.yml
Labels: enhancement

#553 Workflow Submissions: Added email notification for worklfow completion
  app/components/nextflow_component.html.erb
  app/controllers/workflow_executions_controller.rb
  config/locales/en.yml
  test/controllers/workflow_executions_controller_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement, ready for review

#536 Data Export: Add Workflow Executions UI
  app/controllers/data_exports_controller.rb
  app/views/data_exports/_new_export_dialog.html.erb
  app/views/data_exports/_preview.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  app/views/workflow_executions/_attachment.html.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/data_exports_controller_test.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/data_exports.yml
  test/fixtures/files/data_export_7.zip
  test/fixtures/samples.yml
  test/jobs/data_exports/create_job_test.rb
  test/system/data_exports_test.rb
Labels: ready for review

#538 add sapporo docs
  docs-site/docs/development/integration/_category_.json
  docs-site/docs/development/integration/ga4gh_wes_sapporo_setup.md
  docs-site/docs/development/integration/ga4gh_wes_setup.md
Labels: documentation, ready for review

#539 Fix flakey group transfer test
  app/javascript/controllers/transfer_controller.js
  test/system/groups_test.rb
Labels: bug, ready for review

#555 fix flakey completion service tests
  test/services/workflow_executions/completion_service_test.rb
Labels: bug, ready for review

#563 Workflow Execution: Change state to enum
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancel_service.rb
  app/services/workflow_executions/cancelation_service.rb
  app/services/workflow_executions/completion_service.rb
  app/services/workflow_executions/create_service.rb
  app/services/workflow_executions/preparation_service.rb
  app/services/workflow_executions/status_service.rb
  app/services/workflow_executions/submission_service.rb
  app/views/workflow_executions/_workflow_execution.html.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240423155817_change_workflow_execution_state_to_enum.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/models/workflow_execution_test.rb
  test/services/workflow_executions/create_service_test.rb
  test/services/workflow_executions/destroy_service_test.rb
  test/services/workflow_executions/preparation_service_test.rb
  test/services/workflow_executions/status_service_test.rb
  test/system/workflow_executions_test.rb
Labels: ready for review

#567 Add locale to Data Export Mailer
  app/mailers/data_export_mailer.rb
  config/locales/fr.yml
  test/mailers/data_export_mailer_test.rb
Labels: ready for review

#562 Workflow Submission: Change row components to column components for faster turbo updates
  app/components/nextflow/samplesheet/column_component.en.yml
  app/components/nextflow/samplesheet/column_component.html.erb
  app/components/nextflow/samplesheet/column_component.rb
  app/components/nextflow/samplesheet/dropdown_cell_component.html.erb
  app/components/nextflow/samplesheet/metadata_cell_component.html.erb
  app/components/nextflow/samplesheet/metadata_cell_component.rb
  app/components/nextflow/samplesheet/row_component.html.erb
  app/components/nextflow/samplesheet/row_component.rb
  app/components/nextflow/samplesheet/sample_cell_component.html.erb
  app/components/nextflow/samplesheet/text_cell_component.html.erb
  app/components/nextflow/samplesheet_component.en.yml
  app/components/nextflow/samplesheet_component.html.erb
  app/components/nextflow/samplesheet_component.rb
  app/components/nextflow_component.html.erb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/models/sample.rb
  app/views/workflow_executions/metadata/fields.turbo_stream.erb
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  test/components/nextflow_component_test.rb
  test/components/nextflow_samplesheet_component_test.rb
  test/fixtures/files/nextflow/samplesheet_schema_text.json
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement

#546 Workflow executions: Requeue jobs
  app/jobs/workflow_execution_cancelation_job.rb
  app/jobs/workflow_execution_status_job.rb
  app/jobs/workflow_execution_submission_job.rb
  app/services/workflow_executions/cancelation_service.rb
  db/migrate/20240418180337_add_error_code_to_workflow_execution.rb
  db/schema.rb
  lib/integrations/api_exceptions.rb
  lib/integrations/ga4gh_wes_api/v1/api_requester.rb
  test/active_job_test_case.rb
  test/jobs/workflow_execution_cancelation_job_test.rb
  test/jobs/workflow_execution_status_job_test.rb
  test/jobs/workflow_execution_submission_job_test.rb
  test/test_helpers/active_job_test_helpers.rb
Labels: bug, enhancement, database, ready for review

#578 Workflow Submission: Added french translation file for column component
  app/components/nextflow/samplesheet/column_component.fr.yml
  app/components/nextflow/samplesheet_component.fr.yml
Labels: bug

#576 Add missing unique Indexes
  app/models/sample.rb
  db/migrate/20240426144141_add_missing_unique_indexes.rb
  db/schema.rb
Labels: database

#573 Workflow Submission: Add namespace_id to workflow model
  app/components/nextflow_component.html.erb
  app/controllers/workflow_executions_controller.rb
  app/models/workflow_execution.rb
  app/services/automated_workflow_executions/launch_service.rb
  config/schemas/workflow_execution_metadata.json
  db/migrate/20240426160617_add_namespace_ref_to_workflow_execution.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/workflow_executions.yml
  test/models/workflow_execution_test.rb
  test/services/workflow_executions/create_service_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement
