Repository phac-nml/irida-next, pull requests merged in 2024-09, with the labels that each got.

#734 GraphQL: Samples Attachments filtering and ordering
  app/graphql/resolvers/project_samples_resolver.rb
  app/graphql/resolvers/sample_attachments_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/attachment_filter_input_type.rb
  app/graphql/types/attachment_order_input_type.rb
  app/graphql/types/order_direction_type.rb
  app/graphql/types/project_type.rb
  app/graphql/types/sample_type.rb
  app/models/attachment.rb
  config/initializers/active_storage.rb
  test/fixtures/attachments.yml
  test/graphql/attachments_query_test.rb
Labels: ready for review

#738 Enhancement: Select2 component
  app/components/viral/select2_component.html.erb
  app/javascript/controllers/viral/select2_controller.js
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  test/components/previews/viral_select2_component_preview/default.html.erb
  test/components/viral/select2_component_test.rb
Labels: enhancement, ready for review

#743 GraphQL: Samples filtering and ordering
  app/graphql/resolvers/project_samples_resolver.rb
  app/graphql/resolvers/samples_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/project_type.rb
  app/graphql/types/sample_order_input_type.rb
  app/graphql/types/sample_type.rb
  test/graphql/project_samples_query_test.rb
  test/graphql/samples_query_ransack_test.rb
Labels: ready for review, graphql

#744 Bug Fix: Analysis Export with deleted samples
  app/jobs/data_exports/create_job.rb
  test/jobs/data_exports/create_job_test.rb
Labels: bug, ready for review

#733 Groups dashboard searching sorting
  app/components/namespace_tree/namespace_tree_component.html.erb
  app/components/namespace_tree/namespace_tree_component.rb
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/namespace_tree/row_component.rb
  app/components/namespace_tree_container_component.rb
  app/components/viral/dropdown_component.rb
  app/components/viral/pagy/pagination_component.html.erb
  app/components/viral/pagy/pagination_component.rb
  app/controllers/dashboard/groups_controller.rb
  app/models/namespace.rb
  app/policies/group_policy.rb
  app/views/dashboard/groups/index.html.erb
  app/views/dashboard/groups/index.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/policies/group_policy_test.rb
  test/system/dashboard/groups_test.rb
Labels: enhancement

#739 Add Select2 to group and project transfer
  app/javascript/controllers/transfer_controller.js
  app/javascript/controllers/viral/select2_controller.js
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/projects/_transfer_form.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/groups_test.rb
  test/system/projects/transfer_test.rb
Labels: ready for review

#751 Graphql - Add metadata_summary field to Projects
  app/graphql/resolvers/project_metadata_summary_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/project_type.rb
  app/models/project.rb
  test/graphql/projects_query_ransack_test.rb
Labels: ready for review, graphql

#710 Public activity: Projects
  Gemfile
  Gemfile.lock
  app/components/activities/list_item_component.html.erb
  app/components/activities/list_item_component.rb
  app/components/activities/member_activity_component.html.erb
  app/components/activities/member_activity_component.rb
  app/components/activities/namespace_group_link_activity_component.html.erb
  app/components/activities/namespace_group_link_activity_component.rb
  app/components/activities/project_activity_component.html.erb
  app/components/activities/project_activity_component.rb
  app/components/activities/workflow_execution_activity_component.html.erb
  app/components/activities/workflow_execution_activity_component.rb
  app/components/activity_component.html.erb
  app/components/activity_component.rb
  app/controllers/application_controller.rb
  app/controllers/projects_controller.rb
  app/helpers/path_helper.rb
  app/models/concerns/track_activity.rb
  app/models/member.rb
  app/models/namespace.rb
  app/models/namespace_group_link.rb
  app/models/namespaces/project_namespace.rb
  app/services/attachments/create_service.rb
  app/services/attachments/destroy_service.rb
  app/services/automated_workflow_executions/create_service.rb
  app/services/group_links/group_link_service.rb
  app/services/group_links/group_link_update_service.rb
  app/services/group_links/group_unlink_service.rb
  app/services/members/create_service.rb
  app/services/members/destroy_service.rb
  app/services/members/update_service.rb
  app/services/projects/create_service.rb
  app/services/projects/destroy_service.rb
  app/services/projects/transfer_service.rb
  app/services/projects/update_service.rb
  app/services/samples/clone_service.rb
  app/services/samples/create_service.rb
  app/services/samples/destroy_service.rb
  app/services/samples/metadata/update_service.rb
  app/services/samples/transfer_service.rb
  app/services/samples/update_service.rb
  app/services/workflow_executions/completion_service.rb
  app/services/workflow_executions/create_service.rb
  app/views/layouts/projects.html.erb
  app/views/projects/activity.html.erb
  app/views/projects/activity.turbo_stream.erb
  config/i18n-tasks.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  db/migrate/20240423155416_create_activities.rb
  db/schema.rb
  test/components/activity_component_test.rb
  test/components/previews/activity_component_preview.rb
  test/components/previews/activity_component_preview/default.html.erb
  test/fixtures/activities.yml
  test/fixtures/namespace_group_links.yml
  test/test_helper.rb
Labels: enhancement

#749 Graphql - Add ransack filtering and ordering to groups
  app/graphql/resolvers/groups_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/attachment_order_input_type.rb
  app/graphql/types/group_filter_type.rb
  app/graphql/types/group_order_input_type.rb
  app/graphql/types/project_order_input_type.rb
  app/graphql/types/sample_order_input_type.rb
  test/graphql/attachments_query_test.rb
  test/graphql/groups_query_ransack_test.rb
  test/graphql/projects_query_ransack_test.rb
  test/graphql/samples_query_ransack_test.rb
Labels: ready for review, graphql

#759 Fix: Project Attachment Permissions for Bots
  app/models/member.rb
Labels: bug, ready for review

#754 GraphQL - Project Attachment Resolver + AttachFilesToProject Mutation
  app/graphql/mutations/attach_files_to_project.rb
  app/graphql/mutations/attach_files_to_sample.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/resolvers/project_attachments_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  app/graphql/types/project_type.rb
  db/schema.rb
  test/fixtures/active_storage/blobs.yml
  test/graphql/attach_files_to_project_test.rb
  test/graphql/attach_files_to_sample_test.rb
  test/graphql/attachments_query_test.rb
Labels: ready for review, graphql

#765 GraphQL: Use scoped context to skip queries and authorization
  app/graphql/resolvers/project_attachments_resolver.rb
  app/graphql/resolvers/project_sample_resolver.rb
  app/graphql/resolvers/project_samples_resolver.rb
  app/graphql/resolvers/projects_resolver.rb
  app/graphql/resolvers/sample_attachments_resolver.rb
  app/graphql/resolvers/samples_resolver.rb
  app/graphql/types/attachment_type.rb
  app/graphql/types/project_type.rb
  app/graphql/types/sample_type.rb
  test/controllers/projects/samples/attachments_controller_test.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/data_exports.yml
  test/graphql/attachments_query_test.rb
  test/jobs/data_exports/create_job_test.rb
  test/models/attachment_test.rb
  test/services/attachments/create_service_test.rb
  test/system/projects/samples_test.rb
  test/system/workflow_executions_test.rb
Labels: graphql

#756 Clipboard component for copying PUID's
  app/components/clipboard_component.html.erb
  app/components/clipboard_component.rb
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/puid_component.html.erb
  app/components/puid_component.rb
  app/components/token_component.html.erb
  app/components/token_component.rb
  app/components/viral/page_header_component.html.erb
  app/javascript/controllers/clipboard_controller.js
  app/javascript/controllers/token_controller.js
  app/views/groups/bots/_access_token_section.html.erb
  app/views/profiles/personal_access_tokens/_access_token_section.html.erb
  app/views/projects/bots/_access_token_section.html.erb
  app/views/shared/project/_row.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/clipboard_component_test.rb
  test/components/previews/clipboard_component_preview.rb
  test/components/previews/clipboard_component_preview/custom_content.html.erb
  test/components/previews/clipboard_component_preview/default.html.erb
  test/components/previews/puid_component_preview.rb
  test/components/previews/puid_component_preview/default.html.erb
  test/components/previews/token_component_preview.rb
  test/components/previews/token_component_preview/default.html.erb
  test/components/puid_component_test.rb
  test/components/viral/system/token_component_test.rb
  test/system/groups/bots_test.rb
  test/system/projects/bots_test.rb
Labels: enhancement

#763 GraphQL - Group Attachment Resolver + AttachFilesToGroup Mutation
  app/graphql/mutations/attach_files_to_group.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/resolvers/group_attachments_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/attachment_type.rb
  app/graphql/types/group_type.rb
  app/graphql/types/mutation_type.rb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespace_bots.yml
  test/fixtures/personal_access_tokens.yml
  test/fixtures/users.yml
  test/graphql/attach_files_to_group_test.rb
  test/graphql/attachments_query_test.rb
Labels: ready for review, graphql

#735 Samples/counter cache
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/namespace_tree/row/row_contents_component.rb
  app/components/namespace_tree/row/without_children_component.html.erb
  app/components/namespace_tree/row/without_children_component.rb
  app/controllers/projects/samples_controller.rb
  app/models/sample.rb
  app/views/shared/project/_row.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240823185615_add_samples_count_to_projects.rb
  db/migrate/20240823190536_reset_all_project_cache_counters.rb
  db/schema.rb
  test/models/sample_test.rb
  test/system/projects/samples_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: enhancement, database

#762 Project Attachments: Destroy
  app/components/attachments/table_component.html.erb
  app/components/layout_component.html.erb
  app/controllers/projects/attachments_controller.rb
  app/views/projects/attachments/_delete_attachment_modal.html.erb
  app/views/projects/attachments/_table.html.erb
  app/views/projects/attachments/destroy.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/attachments_controller_test.rb
  test/system/projects/attachments_test.rb
Labels: enhancement, ready for review

#766 Data exports table enhancements
  app/components/data_exports/table_component.html.erb
  app/components/data_exports/table_component.rb
  app/controllers/data_exports_controller.rb
  app/models/data_export.rb
  app/views/dashboard/groups/index.html.erb
  app/views/data_exports/_data_export.html.erb
  app/views/data_exports/_table.html.erb
  app/views/data_exports/index.html.erb
  app/views/projects/attachments/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/data_exports_test.rb
Labels: enhancement

#769 Project details UI
  app/components/activities/group_activity_component.html.erb
  app/components/activities/list_item_component.html.erb
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/project_dashboard/activity_component.html.erb
  app/components/project_dashboard/activity_component.rb
  app/components/project_dashboard/information_component.html.erb
  app/components/project_dashboard/information_component.rb
  app/components/project_dashboard/samples_component.html.erb
  app/components/project_dashboard/samples_component.rb
  app/components/project_dashboard_component.html.erb
  app/components/project_dashboard_component.rb
  app/components/viral/tooltip_component.html.erb
  app/controllers/data_exports_controller.rb
  app/controllers/projects_controller.rb
  app/views/projects/show.html.erb
  app/views/shared/project/_row.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/project_dashboard_component_preview.rb
  test/components/previews/project_dashboard_component_preview/default.html.erb
  test/components/project_dashboard_component_test.rb
  test/controllers/projects_controller_test.rb
  test/system/dashboard/projects_test.rb
  test/system/data_exports_test.rb
  test/system/projects/members_test.rb
  test/system/projects_test.rb
Labels: enhancement

#772 Group Attachments: Destroy
  app/components/attachments/table_component.html.erb
  app/components/attachments/table_component.rb
  app/controllers/groups/attachments_controller.rb
  app/views/groups/attachments/_delete_attachment_modal.html.erb
  app/views/groups/attachments/_table.html.erb
  app/views/groups/attachments/destroy.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/group.rb
  test/controllers/groups/attachments_controller_test.rb
  test/system/groups/attachments_test.rb
Labels: ready for review

#770 Enhancement: Created empty search state
  app/components/samples/table_component.html.erb
  app/components/viral/empty_state_component.html.erb
  app/components/viral/pagy/full_component.html.erb
  app/components/viral/pagy/full_component.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/viral_pagy_full_component_preview.rb
  test/components/viral/empty_component_test.rb
  test/components/viral/pagy_full_component_preview_test.rb
  test/system/data_exports_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#775 Fixed dark mode on project details page
  app/components/project_dashboard/information_component.html.erb
  app/components/project_dashboard_component.html.erb
Labels: enhancement

#781 Namespace Attachments: Attachment Actions Concern
  app/controllers/concerns/attachment_actions.rb
  app/controllers/groups/attachments_controller.rb
  app/controllers/projects/attachments_controller.rb
  config/locales/en.yml
  config/locales/fr.yml
Labels: ready for review

#778 Filter by name or puid to projects dashbaord
  app/controllers/dashboard/projects_controller.rb
  app/views/dashboard/projects/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/dashboard/projects_test.rb
Labels: enhancement
