Repository phac-nml/irida-next, pull requests merged in 2024-01, with the labels that each got.

#327 Re-use faraday net_http connections
  Gemfile
  Gemfile.lock
  config/initializers/faraday.rb
  lib/integrations/ga4gh_wes_api/v1/api_connection.rb
Labels: enhancement, ready for review

#363 GraphQL: CreateSample mutation
  app/graphql/mutations/create_sample.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  test/graphql/create_sample_mutation_test.rb
Labels: graphql

#358 Attachments listing update
  app/controllers/projects/samples/attachments/deletions_controller.rb
  app/controllers/projects/samples/attachments_controller.rb
  app/policies/sample_policy.rb
  app/services/attachments/destroy_service.rb
  app/views/projects/samples/attachments/_attachment.html.erb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/projects/samples/attachments/deletions_controller_test.rb
  test/policies/sample_policy_test.rb
  test/services/attachments/destroy_service_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#339 Metadata Summary Update by Metadata::UpdateService
  app/controllers/projects/samples/metadata_controller.rb
  app/models/namespace.rb
  app/models/namespaces/project_namespace.rb
  app/services/samples/metadata/update_service.rb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/policies/group_policy_test.rb
  test/policies/namespace_policy_test.rb
  test/policies/project_policy_test.rb
  test/services/samples/metadata/update_service_test.rb
  test/system/dashboard/projects_test.rb
Labels: ready for review

#364 Add updated_at field to metadata_provenance
  app/services/samples/metadata/update_service.rb
  test/fixtures/samples.yml
  test/services/samples/metadata/update_service_test.rb
Labels: ready for review

#377 GraphQL: Sample Metadata Field Query
  app/graphql/resolvers/sample_metadata_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/sample_type.rb
  test/graphql/samples_query_test.rb
Labels: graphql

#350 Metadata Summary Update by Transfers and Deletions
  app/models/namespace.rb
  app/models/namespaces/project_namespace.rb
  app/services/groups/destroy_service.rb
  app/services/groups/transfer_service.rb
  app/services/projects/destroy_service.rb
  app/services/projects/transfer_service.rb
  app/services/samples/destroy_service.rb
  app/services/samples/transfer_service.rb
  test/services/groups/destroy_service_test.rb
  test/services/groups/transfer_service_test.rb
  test/services/projects/destroy_service_test.rb
  test/services/projects/transfer_service_test.rb
  test/services/samples/destroy_service_test.rb
  test/services/samples/metadata/update_service_test.rb
  test/services/samples/transfer_service_test.rb
Labels: ready for review

#388 Graphql update sample metadata mutation
  app/graphql/mutations/update_sample_metadata.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  test/graphql/update_sample_metadata_test.rb
Labels: graphql

#348 Samples table metadata fields toggle
  Gemfile
  Gemfile.lock
  app/components/viral/time_ago_component.html.erb
  app/controllers/concerns/metadata.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/views/dashboard/projects/index.html.erb
  app/views/dashboard/projects/index.turbo_stream.erb
  app/views/groups/samples/_table.html.erb
  app/views/groups/samples/index.html.erb
  app/views/groups/samples/index.turbo_stream.erb
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/index.turbo_stream.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  app/views/workflow_executions/index.html.erb
  config/application.rb
  config/locales/en.yml
  db/seeds.rb
  test/components/previews/viral_time_ago_component_preview/current_time_input.html.erb
  test/components/previews/viral_time_ago_component_preview/default.html.erb
  test/components/viral/system/time_ago_component_test.rb
  test/fixtures/samples.yml
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#394 GraphQL create direct upload
  .gitignore
  app/graphql/mutations/create_direct_upload.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  config/environments/development.rb
  config/environments/test.rb
  test/graphql/create_direct_upload_test.rb
Labels: enhancement, ready for review, graphql
