Repository phac-nml/irida-next, pull requests merged in 2024-06, with the labels that each got.

#630 Fix: Metadata Fields retrieval for Shared Groups and Shared Projects [DFCT0010073]
  app/controllers/concerns/metadata.rb
  app/models/group.rb
  app/models/namespace.rb
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/samples.yml
  test/models/group_test.rb
  test/system/groups/samples_test.rb
Labels: bug

#619 Docs: Add Data Export User Docs
  docs-site/docs/user/export/export-types.md
  docs-site/docs/user/export/getting-started.md
  docs-site/docs/user/export/working-with-exports.md
Labels: ready for review

#632 Documentation site dependency update
  .tool-versions
  docs-site/docusaurus.config.js
  docs-site/package.json
  docs-site/pnpm-lock.yaml
Labels: dependencies

#633 [ENHC0010029] Add TSV support for Metadata imports
  app/services/samples/metadata/file_import_service.rb
  app/views/projects/samples/metadata/file_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/files/metadata/valid.tsv
  test/services/samples/metadata/file_import_service_test.rb
Labels: enhancement, ready for review

#634 Fix errors in the README file
  README.md
Labels: documentation

#508 [ENHC0010032] List samples within transfer dialog
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/infinite_scroll_controller.js
  app/javascript/controllers/projects/samples/attachments/selected_attachments_controller.js
  app/javascript/controllers/projects/samples/metadata/destroy_controller.js
  app/javascript/controllers/selection_controller.js
  app/javascript/controllers/sessionstorage_amend_form_controller.js
  app/javascript/controllers/spinner_controller.js
  app/javascript/utilities/form.js
  app/views/projects/samples/_list_sample.html.erb
  app/views/projects/samples/list.turbo_stream.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples_controller_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#625 GraphQL: Add isPuid query
  app/graphql/resolvers/is_puid_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/query_type.rb
  lib/irida/persistent_unique_id.rb
  test/graphql/is_puid_query_test.rb
Labels: ready for review, graphql

#640 [ENHC0010033] List samples within clone dialog
  app/javascript/controllers/infinite_scroll_controller.js
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  app/views/shared/loading/_samples_list_skeleton.html.erb
  app/views/shared/loading/_spinner.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/projects/samples_test.rb
Labels: enhancement

#623 Docs: Project and Sample
  docs-site/docs/user/organization/members/group-and-project-members.md
  docs-site/docs/user/project/projects/manage-projects.md
  docs-site/docs/user/project/projects/projects-intro.md
  docs-site/docs/user/project/samples/manage-samples.md
  docs-site/docs/user/project/samples/sample-files.md
  docs-site/docs/user/project/samples/sample-metadata.md
  docs-site/docs/user/project/samples/samples-intro.md
Labels: ready for review

#649 [DFCT0010089] Fix groups being able to recursively share to themselves
  app/controllers/concerns/share_actions.rb
  app/models/namespace_group_link.rb
  app/services/group_links/group_link_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/concerns/group_share_actions_concern_test.rb
  test/controllers/groups/group_links_controller_test.rb
  test/controllers/projects/group_links_controller_test.rb
  test/models/namespace_group_link_test.rb
  test/services/group_links/group_link_service_test.rb
Labels: bug, database, ready for review

#631 Display samples for workflow execution (ENHC0010030)
  app/components/nextflow/samplesheet/column_component.rb
  app/components/nextflow/samplesheet/dropdown_cell_component.html.erb
  app/components/nextflow_component.html.erb
  app/controllers/concerns/workflow_execution_actions.rb
  app/views/workflow_executions/_params.html.erb
  app/views/workflow_executions/_samplesheet.html.erb
  app/views/workflow_executions/_summary.html.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/nextflow_samplesheet_component_test.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/policies/workflow_execution_policy_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#629 [ENHC0010020] Delete multiple samples from project samples table
  app/components/samples/table_component.html.erb
  app/controllers/projects/samples/attachments_controller.rb
  app/controllers/projects/samples/deletions_controller.rb
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/infinite_scroll_controller.js
  app/javascript/controllers/selection_controller.js
  app/services/samples/destroy_service.rb
  app/views/projects/samples/attachments/_attachment.html.erb
  app/views/projects/samples/attachments/_delete_attachment_modal.html.erb
  app/views/projects/samples/attachments/destroy.turbo_stream.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/deletions/_new_deletion_dialog.html.erb
  app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb
  app/views/projects/samples/deletions/destroy.turbo_stream.erb
  app/views/projects/samples/deletions/destroy_multiple.turbo_stream.erb
  app/views/projects/samples/destroy.turbo_stream.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/show.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples/attachments_controller_test.rb
  test/controllers/projects/samples/deletions_controller_test.rb
  test/controllers/projects/samples_controller_test.rb
  test/services/samples/destroy_service_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#651 Sample filtering when manually entering samples results in cursor moving to next sample entry if there is a pause (DFCT0010081)
  app/components/list_filter_component.html.erb
  app/javascript/controllers/list_filter_controller.js
  test/components/viral/system/list_filter_component_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement
