Repository phac-nml/irida-next, pull requests merged in 2024-05, with the labels that each got.

#579 Workflow Submission: Add custom name to a workflow execution
  app/components/nextflow_component.en.yml
  app/components/nextflow_component.fr.yml
  app/components/nextflow_component.html.erb
  app/controllers/projects/automated_workflow_executions_controller.rb
  app/controllers/workflow_executions_controller.rb
  app/models/workflow_execution.rb
  app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
  app/views/projects/automated_workflow_executions/_table.html.erb
  app/views/workflow_executions/_table.html.erb
  app/views/workflow_executions/_workflow_execution.html.erb
  config/locales/en.yml
  db/migrate/20240426160117_add_name_to_workflow_execution.rb
  db/migrate/20240501131412_add_name_to_automated_workflow_execution.rb
  db/schema.rb
  test/components/nextflow_component_test.rb
  test/controllers/projects/automated_workflow_executions_controller_test.rb
  test/fixtures/automated_workflow_executions.yml
  test/models/automated_workflow_execution_test.rb
  test/services/workflow_executions/create_service_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#584 Update Model Tests
  app/models/namespace_bot.rb
  test/fixtures/namespace_bots.yml
  test/models/attachment_test.rb
  test/models/automated_workflow_execution_test.rb
  test/models/concerns/has_puid_test.rb
  test/models/concerns/has_user_type_test.rb
  test/models/namespace_bot_test.rb
  test/models/namespace_group_link_test.rb
  test/models/namespaces/project_namespace_test.rb
  test/models/namespaces/user_namespace_test.rb
  test/models/project_test.rb
  test/models/route_test.rb
  test/models/sample_test.rb
  test/models/user_test.rb
Labels: ready for review

#589 Workflow execution show: Display pipeline parameters
  app/controllers/workflow_executions_controller.rb
  app/views/projects/samples/show.html.erb
  app/views/workflow_executions/_params.html.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  test/fixtures/workflow_executions.yml
  test/policies/workflow_execution_policy_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#591 Redirect dashboard index to dashboard projects
  app/controllers/concerns/membership_actions.rb
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.erb
  app/views/layouts/devise.html.erb
  test/controllers/dashboard_controller_test.rb
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/routes.yml
  test/system/projects/members_test.rb
Labels: ready for review

#594 Automated Workflow Executions: Update
  app/components/nextflow_component.html.erb
  app/components/nextflow_component.rb
  app/controllers/projects/automated_workflow_executions_controller.rb
  app/helpers/nextflow_helper.rb
  app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
  app/views/projects/automated_workflow_executions/_edit_dialog.html.erb
  app/views/projects/automated_workflow_executions/_table.html.erb
  app/views/projects/automated_workflow_executions/edit.html.erb
  app/views/projects/automated_workflow_executions/update.turbo_stream.erb
  config/locales/en.yml
  test/system/projects/automated_workflow_executions_test.rb
Labels: enhancement, ready for review

#590 Project workflow executions UI
  app/controllers/concerns/workflow_execution_actions.rb
  app/controllers/projects/workflow_executions_controller.rb
  app/controllers/workflow_executions_controller.rb
  app/models/member.rb
  app/policies/workflow_execution_policy.rb
  app/views/layouts/projects.html.erb
  app/views/projects/workflow_executions/_attachment.html.erb
  app/views/projects/workflow_executions/_files.html.erb
  app/views/projects/workflow_executions/_pagination.html.erb
  app/views/projects/workflow_executions/_params.html.erb
  app/views/projects/workflow_executions/_summary.html.erb
  app/views/projects/workflow_executions/_table.html.erb
  app/views/projects/workflow_executions/_workflow_execution.html.erb
  app/views/projects/workflow_executions/cancel.turbo_stream.erb
  app/views/projects/workflow_executions/destroy.turbo_stream.erb
  app/views/projects/workflow_executions/index.html.erb
  app/views/projects/workflow_executions/index.turbo_stream.erb
  app/views/projects/workflow_executions/show.html.erb
  config/locales/en.yml
  test/controllers/projects/workflow_executions_controller_test.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/policies/workflow_execution_policy_test.rb
  test/system/projects/workflow_executions_test.rb
Labels: enhancement

#598 Metadata File Import: Allow Sample PUIDs
  app/services/samples/metadata/file_import_service.rb
  lib/irida/persistent_unique_id.rb
  test/fixtures/files/metadata/valid_with_puid.csv
  test/services/samples/metadata/file_import_service_test.rb
Labels: bug

#596 Table style cleanup
  app/views/groups/members/_member.html.erb
  app/views/groups/members/_member_listing.html.erb
  app/views/groups/samples/_table.html.erb
  app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
  app/views/projects/members/_member.html.erb
  app/views/projects/members/_member_listing.html.erb
  app/views/projects/samples/_table.html.erb
  app/views/projects/samples/attachments/_attachment.html.erb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/workflow_executions/_attachment.html.erb
  app/views/projects/workflow_executions/_files.html.erb
  app/views/workflow_executions/_files.html.erb
  test/system/groups/members_test.rb
  test/system/projects/samples_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#602 Replace all old gray colours to slate
  app/components/updated_component.html.erb
  app/components/viral/form/datepicker_component.html.erb
  app/components/viral/form/file_input_component.html.erb
  app/components/viral/pill_component.rb
  app/views/data_exports/_data_export.html.erb
  app/views/data_exports/_summary.html.erb
  app/views/groups/_edit_advanced_transfer.html.erb
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/group_links/_invited_groups.html.erb
  app/views/groups/group_links/_namespace_group_link.html.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/groups/members/_member.html.erb
  app/views/layouts/projects.html.erb
  app/views/profiles/preferences/_locale_form.html.erb
  app/views/profiles/preferences/show.html.erb
  app/views/projects/_change_path.html.erb
  app/views/projects/_destroy.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/group_links/_invited_groups.html.erb
  app/views/projects/group_links/_namespace_group_link.html.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/members/_member.html.erb
  app/views/projects/members/index.html.erb
  app/views/projects/samples/attachments/concatenations/_modal.html.erb
  app/views/projects/samples/attachments/deletions/_modal.html.erb
  app/views/projects/samples/metadata/deletions/_modal.html.erb
  app/views/projects/workflow_executions/_workflow_execution.html.erb
  app/views/workflow_executions/_workflow_execution.html.erb
  app/views/workflow_executions/submissions/_pipeline_selection_dialog.html.erb
  test/components/previews/confirmation_component_preview/with_confirm_value.html.erb
  test/components/previews/selection_preview/default.html.erb
  test/components/previews/selection_preview/with_a_storage_key.html.erb
  test/components/previews/selection_preview/within_a_table.html.erb
  test/components/previews/viral_card_component_preview/section_with_action.html.erb
  test/components/previews/viral_card_component_preview/titled_sections.html.erb
  test/components/previews/viral_card_component_preview/with_multiple_sections.html.erb
  test/components/previews/viral_dialog_component_preview/confirmation.html.erb
  test/components/previews/viral_dialog_component_preview/default.html.erb
  test/components/previews/viral_dialog_component_preview/extra_large.html.erb
  test/components/previews/viral_dialog_component_preview/large.html.erb
  test/components/previews/viral_dialog_component_preview/small.html.erb
  test/components/previews/viral_dialog_component_preview/with_action_buttons.html.erb
  test/components/previews/viral_dialog_component_preview/with_multiple_sections.html.erb
  test/components/previews/viral_dialog_component_preview/with_trigger.html.erb
  test/components/previews/viral_pill_component_preview/with_classes.html.erb
  test/components/previews/viral_tabs_component_preview/default.html.erb
  test/components/previews/viral_time_ago_component_preview/current_time_input.html.erb
  test/components/previews/viral_time_ago_component_preview/default.html.erb
  test/components/viral/pill_component_test.rb
  test/system/data_exports_test.rb
Labels: enhancement

#611 [DFCT0010053] Fix labels when showing parameter summary
  app/components/nextflow_component.html.erb
  app/controllers/concerns/workflow_execution_actions.rb
  app/controllers/projects/automated_workflow_executions_controller.rb
  app/controllers/workflow_executions/submissions_controller.rb
  app/helpers/nextflow_helper.rb
  app/services/automated_workflow_executions/launch_service.rb
  app/services/workflow_executions/create_service.rb
  app/services/workflow_executions/preparation_service.rb
  app/views/workflow_executions/_params.html.erb
  config/initializers/pipelines.rb
  lib/irida/pipelines.rb
  test/lib/irida/pipelines_overrides_test.rb
  test/lib/irida/pipelines_schema_test.rb
  test/lib/irida/pipelines_test.rb
Labels: bug

#613 Fix: Confirmation component accessibility (DFCT0010064)
  app/components/confirmation_component.html.erb
  app/components/list_filter_component.html.erb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  app/javascript/controllers/sessionstorage_amend_form_controller.js
  app/javascript/controllers/viral/dialog_controller.js
  app/views/dashboard/groups/index.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  config/locales/en.yml
  test/components/viral/system/confirmation_component_test.rb
  test/components/viral/system/dialog_component_test.rb
  test/components/viral/system/flash_component_test.rb
  test/components/viral/system/list_filter_component_test.rb
  test/system/data_exports_test.rb
  test/system/groups_test.rb
  test/system/projects/samples_test.rb
  test/system/projects/transfer_test.rb
  test/system/projects_test.rb
  test/test_helper.rb
  test/view_component_system_test_case.rb
Labels: bug

#614 Fix: Bot account membership destroy (DFCT0010061)
  app/models/namespace_bot.rb
  app/models/user.rb
  config/locales/en.yml
  db/migrate/20240523185248_remove_bot_account_memberships.rb
  db/schema.rb
  test/models/namespace_bot_test.rb
  test/services/automated_workflow_executions/launch_service_test.rb
  test/services/bots/destroy_service_test.rb
Labels: bug

#605 [ENHC0010012] Workflow executions/cleanup Service
  app/helpers/blob_helper.rb
  app/services/workflow_executions/cleanup_service.rb
  app/services/workflow_executions/preparation_service.rb
  db/migrate/20240508171227_add_cleaned_boolean_workflow_execution.rb
  db/schema.rb
  test/fixtures/files/samplesheet.csv
  test/services/workflow_executions/cleanup_service_test.rb
  test/test_helpers/blob_test_helpers.rb
Labels: enhancement, database, ready for review

#581 [ENHC0010012A] Workflow executions: Cleanup job + service code flow
  app/jobs/workflow_execution_cancelation_job.rb
  app/jobs/workflow_execution_cleanup_job.rb
  app/jobs/workflow_execution_status_job.rb
  app/jobs/workflow_execution_submission_job.rb
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancel_service.rb
  app/services/workflow_executions/cancelation_service.rb
  app/services/workflow_executions/completion_service.rb
  app/services/workflow_executions/status_service.rb
  docs-site/docs/development/integration/workflow_execution_code_flow.md
  docs-site/static/img/workflow_execution_code2flow.png
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/files/test_file_end_to_end_F.fastq
  test/fixtures/files/test_file_end_to_end_R.fastq
  test/fixtures/groups.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/samples.yml
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/users.yml
  test/fixtures/workflow_executions.yml
  test/jobs/workflow_execution_cancelation_job_test.rb
  test/jobs/workflow_execution_cleanup_job_test.rb
  test/jobs/workflow_execution_status_job_test.rb
  test/jobs/workflow_execution_submission_job_test.rb
  test/models/workflow_execution_test.rb
  test/policies/workflow_execution_policy_test.rb
  test/services/workflow_executions/destroy_service_test.rb
  test/system/dashboard/projects_test.rb
  test/system/workflow_executions_test.rb
  test/test_helpers/active_job_test_helpers.rb
Labels: enhancement, database

#620 GraphQL: Add projectSample query [DFCT0010065]
  .gitignore
  Gemfile.lock
  app/graphql/irida_schema.rb
  app/graphql/resolvers/project_sample_resolver.rb
  app/graphql/resolvers/sample_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/query_type.rb
  app/policies/namespace_policy.rb
  app/policies/project_policy.rb
  config/storage.yml
  test/fixtures/active_storage/blobs.yml
  test/graphql/project_sample_query_test.rb
  test/graphql/project_samples_query_test.rb
  test/lib/irida/pipelines_overrides_test.rb
  test/lib/irida/pipelines_schema_test.rb
  test/lib/irida/pipelines_test.rb
  test/system/dashboard/groups_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
  test/test_helper.rb
Labels: ready for review

#621 [ENHC0010012B] Workflow executions: End to end integration test
  .github/workflows/sapporo.yml
  Gemfile
  Gemfile.lock
  config/application.rb
  lib/integrations/ga4gh_wes_api/v1/api_connection.rb
  scripts/clean_dev.sh
  test/integration/sapporo.rb
Labels: security, ready for review
