Repository phac-nml/irida-next, pull requests merged in 2024-12, with the labels that each got.

#848 Data Table: Projects Automated Pipelines
  app/components/viral/data_table/column_component.rb
  app/views/projects/automated_workflow_executions/_automated_workflow_execution.html.erb
  app/views/projects/automated_workflow_executions/_table.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/projects/automated_workflow_executions_test.rb
Labels: ready for review

#845 Switch from Azure AD to Entra ID
  Gemfile
  Gemfile.lock
  app/assets/icons/heroicons/entra_id.svg
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  config/authentication/auth_config.yml
  config/initializers/devise.rb
  db/migrate/20241120173553_azure_ad_to_entra_id.rb
  db/schema.rb
  docs-site/docs/configuration/authentication.md
  test/helpers/view_helper_test.rb
  test/integration/omniauth_callbacks_test.rb
  test/system/sign_in_display_test.rb
  test/test_helpers/omniauth_helpers.rb
Labels: ready for review, dependencies

#857 Fixed issue with name not displaying on workflow show page
  app/views/workflow_executions/show.html.erb
Labels: bug

#861 Sidebar enhancements
  app/components/layout/sidebar/header_component.html.erb
  app/components/layout/sidebar/header_component.rb
  app/components/layout/sidebar_component.html.erb
  app/components/layout/sidebar_component.rb
  app/components/viral/avatar_component.rb
  app/views/groups/update.turbo_stream.erb
  app/views/layouts/application.html.erb
  app/views/layouts/groups.html.erb
  app/views/layouts/profiles.html.erb
  app/views/layouts/projects.html.erb
  app/views/projects/update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/layout/sidebar_component_test.rb
  test/components/layout_component_test.rb
  test/system/groups_test.rb
  test/system/projects_test.rb
Labels: enhancement, ready for review

#865 Refactor: Split projects/samples_test
  test/system/projects/samples/attachments_test.rb
  test/system/projects/samples/history_test.rb
  test/system/projects/samples/metadata_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#868 dependency: Update view_component gem to version 3.20.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#832 Graphql/workflow execution query
  app/graphql/irida_schema.rb
  app/graphql/resolvers/samples_workflow_executions_resolver.rb
  app/graphql/resolvers/workflow_execution_metadata_resolver.rb
  app/graphql/resolvers/workflow_executions_resolver.rb
  app/graphql/schema.graphql
  app/graphql/types/query_type.rb
  app/graphql/types/samples_workflow_execution_type.rb
  app/graphql/types/workflow_execution_type.rb
  test/fixtures/workflow_executions.yml
  test/graphql/workflow_executions_query_test.rb
Labels: ready for review, graphql

#849 Data Table: Bot Accounts
  app/components/bots/table_component.html.erb
  app/components/bots/table_component.rb
  app/components/personal_access_tokens/table_component.html.erb
  app/components/personal_access_tokens/table_component.rb
  app/controllers/concerns/bot_actions.rb
  app/controllers/concerns/bot_personal_access_token_actions.rb
  app/controllers/groups/bots_controller.rb
  app/controllers/projects/bots_controller.rb
  app/views/groups/bots/_access_token_section.html.erb
  app/views/groups/bots/_bot.html.erb
  app/views/groups/bots/_bot_listing.html.erb
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/bots/_pagination.html.erb
  app/views/groups/bots/_table.html.erb
  app/views/groups/bots/create.turbo_stream.erb
  app/views/groups/bots/destroy.turbo_stream.erb
  app/views/groups/bots/index.html.erb
  app/views/groups/bots/index.turbo_stream.erb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_personal_access_token.html.erb
  app/views/groups/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_table.html.erb
  app/views/groups/bots/personal_access_tokens/create.turbo_stream.erb
  app/views/groups/bots/personal_access_tokens/revoke.turbo_stream.erb
  app/views/profiles/personal_access_tokens/_table.html.erb
  app/views/projects/bots/_access_token_section.html.erb
  app/views/projects/bots/_bot.html.erb
  app/views/projects/bots/_bot_listing.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/_pagination.html.erb
  app/views/projects/bots/_table.html.erb
  app/views/projects/bots/create.turbo_stream.erb
  app/views/projects/bots/destroy.turbo_stream.erb
  app/views/projects/bots/generate_personal_access_token.turbo_stream.erb
  app/views/projects/bots/index.html.erb
  app/views/projects/bots/index.turbo_stream.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_personal_access_token.html.erb
  app/views/projects/bots/personal_access_tokens/_personal_access_token_listing_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_table.html.erb
  app/views/projects/bots/personal_access_tokens/create.turbo_stream.erb
  app/views/projects/bots/personal_access_tokens/index.turbo_stream.erb
  app/views/projects/bots/personal_access_tokens/revoke.turbo_stream.erb
  app/views/workflow_executions/submissions/create.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/concerns/bot_actions_concern_test.rb
  test/controllers/groups/bots_controller_test.rb
  test/controllers/projects/bots_controller_test.rb
  test/system/groups/bots_test.rb
  test/system/profile_test.rb
  test/system/projects/bots_test.rb
Labels: ready for review

#873 Samples Table: Determine query type
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/models/sample/query.rb
Labels: ready for review

#860 Data Table Bot Accounts: Remove PAT panel on destroy
  app/components/bots/table_component.html.erb
  app/components/bots/table_component.rb
  app/components/personal_access_tokens/table_component.html.erb
  app/components/personal_access_tokens/table_component.rb
  app/controllers/concerns/bot_actions.rb
  app/controllers/concerns/bot_personal_access_token_actions.rb
  app/javascript/controllers/token_controller.js
  app/views/groups/bots/_destroy_confirmation_modal.html.erb
  app/views/groups/bots/index.html.erb
  app/views/groups/bots/personal_access_tokens/_revoke_confirmation_modal.html.erb
  app/views/projects/bots/_destroy_confirmation_modal.html.erb
  app/views/projects/bots/index.html.erb
  app/views/projects/bots/personal_access_tokens/_revoke_confirmation_modal.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/group.rb
  config/routes/project.rb
  test/controllers/concerns/bot_actions_concern_test.rb
  test/controllers/concerns/bot_personal_access_token_actions_concern_test.rb
  test/system/groups/bots_test.rb
  test/system/projects/bots_test.rb
Labels: ready for review
