Repository phac-nml/irida-next, pull requests merged in 2025-05, with the labels that each got.

#1035 Batch import UI: Metadata (part 2)
  app/controllers/groups/samples/spreadsheet_imports_controller.rb
  app/controllers/projects/samples/spreadsheet_imports_controller.rb
  app/javascript/controllers/spreadsheet_import_controller.js
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/services/samples/batch_file_import_service.rb
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/samples/group_batch_sample_import_service_test.rb
  test/services/samples/project_batch_sample_import_service_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#1049 Enhance accessibility for pagy components with ARIA labels
  .vscode/settings.json
  app/components/nextflow/samplesheet_component.html.erb
  app/components/pagination_component.html.erb
  app/components/viral/pagy/limit_component.html.erb
  app/components/viral/pagy/pagination_component.html.erb
  app/components/viral/pagy/pagination_component.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/pagination_component_test.rb
  test/components/viral/pagy_full_component_preview_test.rb
  test/components/viral/pagy_pagination_component_preview_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/members_test.rb
  test/system/groups/metadata_templates_test.rb
  test/system/projects/members_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/workflow_executions_test.rb
Labels: accessibility

#1051 Fix: Group Samples Index
  app/controllers/groups/samples_controller.rb
  app/views/groups/samples/index.html.erb
  test/system/groups/samples_test.rb
Labels: ready for review

#1053 accessibility: Fixed attachments table sort aria
  app/components/attachments/table_component.html.erb
  app/components/attachments/table_component.rb
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
Labels: ready for review, accessibility

#986 Project Workflow Executions: Destroy Activity
  app/components/activities/dialogs/activity_list_dialog_component.html.erb
  app/components/activities/dialogs/activity_list_dialog_component.rb
  app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb
  app/components/activities/dialogs/activity_table_listing_dialog_component.rb
  app/components/activities/dialogs/sample_activity_table_listing_dialog_component.rb
  app/components/activities/list_item_component.html.erb
  app/components/activities/list_item_component.rb
  app/components/activities/projects/workflow_execution_activity_component.html.erb
  app/components/activities/projects/workflow_execution_activity_component.rb
  app/controllers/activities_controller.rb
  app/javascript/controllers/activities/extended_details_controller.js
  app/models/concerns/track_activity.rb
  app/services/workflow_executions/destroy_service.rb
  app/views/shared/workflow_executions/_destroy_multiple_confirmation_dialog.html.erb
  app/views/shared/workflow_executions/_list_workflow_execution.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/activities/dialogs/activity_list_dialog_component_test.rb
  test/components/activities/dialogs/activity_table_listing_dialog_component_test.rb
  test/components/activity_component_test.rb
  test/components/projects/workflow_execution_activity_component.rb
  test/controllers/activities_controller_test.rb
  test/fixtures/activity_extended_details.yml
  test/fixtures/extended_details.yml
  test/fixtures/public_activity/activities.yml
  test/services/workflow_executions/destroy_service_test.rb
Labels: ready for review

#1055 Batch Sample Import: Direct Upload
  app/controllers/concerns/sample_spreadsheet_import_actions.rb
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/groups/samples/spreadsheet_import_controller_test.rb
  test/controllers/projects/samples/spreadsheet_import_controller_test.rb
  test/fixtures/active_storage/blobs.yml
  test/fixtures/files/valid_group_sample_import.csv
  test/fixtures/files/valid_project_sample_import.csv
Labels: ready for review

#1052 accessibility: Fixed workflow executions table sort aria
  app/components/workflow_executions/table_component.html.erb
  app/components/workflow_executions/table_component.rb
  test/system/groups/workflow_executions_test.rb
  test/system/projects/workflow_executions_test.rb
Labels: ready for review, accessibility

#1056 Batch Sample Import: Extend Activities
  app/components/activities/dialogs/activity_list_dialog_component.rb
  app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb
  app/components/activities/dialogs/activity_table_listing_dialog_component.rb
  app/components/activities/groups/sample_activity_component.html.erb
  app/components/activities/groups/sample_activity_component.rb
  app/components/activities/list_item_component.rb
  app/components/activities/projects/sample_activity_component.html.erb
  app/components/activities/projects/sample_activity_component.rb
  app/controllers/activities_controller.rb
  app/javascript/controllers/activities/extended_details_controller.js
  app/models/concerns/track_activity.rb
  app/services/samples/batch_file_import_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/activities/dialogs/activity_list_dialog_component_test.rb
  test/components/activities/dialogs/activity_table_listing_dialog_component_test.rb
  test/components/projects/sample_activity_component_test.rb
  test/fixtures/activity_extended_details.yml
  test/fixtures/extended_details.yml
  test/fixtures/files/batch_sample_import/group/valid_with_multiple_project_puids.csv
  test/fixtures/public_activity/activities.yml
  test/services/samples/group_batch_sample_import_service_test.rb
  test/services/samples/project_batch_sample_import_service_test.rb
Labels: ready for review

#1057 Project details reflow
  app/components/project_dashboard/information_component.html.erb
  app/components/project_dashboard/samples_component.html.erb
  app/components/project_dashboard_component.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: enhancement, ready for review, accessibility

#1058 Breadcrumb accessibility
  app/assets/icons/heroicons/chevron_left.svg
  app/components/activities/dialogs/activity_list_dialog_component.rb
  app/components/layout/language_selection_component.html.erb
  app/components/layout/sidebar_component.html.erb
  app/components/layout_component.html.erb
  app/components/pagination_component.html.erb
  app/components/pagination_component.rb
  app/components/viral/breadcrumb_component.html.erb
  app/components/viral/breadcrumb_component.rb
  app/components/viral/dropdown/item_component.html.erb
  app/components/viral/dropdown_component.html.erb
  app/components/viral/dropdown_component.rb
  app/javascript/controllers/language_selection_dd_controller.js
  app/javascript/controllers/viral/dropdown_controller.js
  config/locales/en.yml
  config/locales/fr.yml
  test/components/layout_component_test.rb
  test/components/pagination_component_test.rb
  test/components/viral/breadcrumb_component_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/members_test.rb
  test/system/groups/metadata_templates_test.rb
  test/system/profile_test.rb
  test/system/projects/members_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/workflow_executions_test.rb
Labels: ready for review, accessibility

#1066 Fix for sorting samples table by project column
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  config/i18n-tasks.yml
  config/locales/en.yml
  config/locales/fr.yml
  test/components/samples/table_component_test.rb
Labels: bug

#1062 Import Metadata UI: Enhancements
  app/javascript/controllers/metadata/file_import_controller.js
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/views/shared/metadata_templates/_edit_template_dialog.html.erb
  app/views/shared/metadata_templates/_new_template_dialog.html.erb
  app/views/shared/samples/metadata/file_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/files/metadata/contains_ignored_headers.csv
  test/system/groups/metadata_templates_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#1070 Update buttons on Projects dashboard to meet size requirement for siteimprove
  app/assets/tailwind/application.css
  app/components/activities/groups/sample_activity_component.html.erb
  app/components/activities/projects/sample_activity_component.html.erb
  app/components/activities/projects/sample_clone_activity_component.html.erb
  app/components/activities/projects/sample_transfer_activity_component.html.erb
  app/components/activities/projects/workflow_execution_activity_component.html.erb
  app/components/layout/sidebar_component.html.erb
  app/components/pagination_component.html.erb
  app/components/viral/button_component.rb
  test/components/viral/button_component_test.rb
Labels: enhancement

#1063 Samples tabs cleanup
  app/assets/icons/heroicons/table_cells.svg
  app/components/puid_component.html.erb
  app/components/viral/empty_state_component.html.erb
  app/components/viral/empty_state_component.rb
  app/controllers/projects/samples/attachments_controller.rb
  app/controllers/samples/metadata_controller.rb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/samples/attachments/create.turbo_stream.erb
  app/views/projects/samples/metadata/_new_metadata_modal.html.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/projects/samples/metadata/deletions/_modal.html.erb
  app/views/projects/samples/metadata/destroy.turbo_stream.erb
  app/views/projects/samples/show.html.erb
  app/views/samples/metadata/bulk_create.turbo_stream.erb
  app/views/samples/metadata/bulk_update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/viral/empty_component_test.rb
  test/components/viral/empty_state_component_test.rb
  test/components/viral/pagy_full_component_preview_test.rb
  test/system/data_exports_test.rb
  test/system/groups/attachments_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/attachments_test.rb
  test/system/projects/samples/attachments_test.rb
  test/system/projects/samples/metadata_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#1073 Updates accessibility of pagination component
  app/components/viral/pagy/limit_component.html.erb
  app/components/viral/pagy/pagination_component.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/viral/pagy_pagination_component_preview_test.rb
Labels: accessibility

#1071 Enhance FlashComponent with improved accessibility support and styling
  app/components/viral/flash_component.html.erb
  app/components/viral/flash_component.rb
  test/components/previews/viral/flash_component_preview.rb
  test/components/previews/viral_flash_component_preview.rb
  test/components/previews/viral_flash_component_preview/error_flash.html.erb
  test/components/previews/viral_flash_component_preview/info_flash.html.erb
  test/components/previews/viral_flash_component_preview/success_flash.html.erb
  test/components/previews/viral_flash_component_preview/warning_flash.html.erb
  test/components/viral/flash_component_test.rb
  test/components/viral/system/flash_component_test.rb
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
Labels: enhancement

#1087 Fix accessibility of the multi level menu component
  app/components/layout/sidebar/multi_level_menu_component.html.erb
  app/javascript/controllers/collapsible_controller.js
Labels: accessibility

#1083 Delete sample selection fix
  app/views/projects/samples/deletions/_new_deletion_dialog.html.erb
  app/views/projects/samples/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/dashboard/projects_test.rb
  test/system/projects/samples_test.rb
Labels: bug

#1077 Delete workflow execution selection fix
  app/components/workflow_executions/table_component.html.erb
  app/components/workflow_executions/table_component.rb
  app/controllers/concerns/workflow_execution_actions.rb
  app/controllers/projects/workflow_executions_controller.rb
  app/controllers/workflow_executions_controller.rb
  app/javascript/controllers/selection_controller.js
  app/views/projects/workflow_executions/destroy.turbo_stream.erb
  app/views/projects/workflow_executions/show.html.erb
  app/views/shared/workflow_executions/_destroy_confirmation_dialog.html.erb
  app/views/workflow_executions/destroy.turbo_stream.erb
  app/views/workflow_executions/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  config/routes/workflow_executions.rb
  test/controllers/projects/workflow_executions_controller_test.rb
  test/controllers/workflow_executions_controller_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: bug

#1074 Sample Actions Cleanup
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  test/system/data_exports_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#1064 Nextflow Samplesheet: Convert to HTML Table
  app/components/nextflow/samplesheet/header_component.html.erb
  app/components/nextflow/samplesheet_component.html.erb
  app/components/nextflow_component.html.erb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/views/workflow_executions/file_selector/create.turbo_stream.erb
  app/views/workflow_executions/metadata/fields.turbo_stream.erb
  test/components/nextflow_samplesheet_component_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review

#1078 Group Information Sidebar
  app/components/namespace_statistic_component.html.erb
  app/components/namespace_statistic_component.rb
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/project_dashboard/information_component.html.erb
  app/components/project_dashboard/samples_component.html.erb
  app/components/project_dashboard_component.html.erb
  app/views/groups/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/namespace_statistic_component_test.rb
  test/components/previews/namespace_statistic_component_preview.rb
Labels: enhancement, ready for review

#1080 Tweaking sidebar colours
  app/components/layout/sidebar/header_component.html.erb
  app/components/layout/sidebar/item_component.html.erb
  app/components/layout/sidebar/item_component.rb
  app/components/layout/sidebar/multi_level_menu_component.html.erb
  app/components/layout/sidebar/multi_level_menu_component.rb
  app/components/layout/sidebar/section_component.html.erb
  app/components/layout/sidebar_component.html.erb
  app/components/layout/sidebar_component.rb
  app/components/layout_component.html.erb
  app/components/viral/avatar_component.rb
  app/components/viral/pagy/pagination_component.html.erb
  app/helpers/icon_helper.rb
  app/javascript/controllers/collapsible_controller.js
  app/javascript/controllers/sidebar_item_controller.js
  app/views/groups/update.turbo_stream.erb
  app/views/layouts/groups.html.erb
  app/views/layouts/projects.html.erb
  app/views/projects/update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/layout/sidebar_component_test.rb
  test/components/layout_component_test.rb
  test/components/viral/avatar_component_test.rb
  test/components/viral/page_header_component_test.rb
Labels: ready for review

#1084 Automated Workflow Execution: Update name to include sample name
  app/services/automated_workflow_executions/launch_service.rb
  test/services/automated_workflow_executions/launch_service_test.rb
Labels: enhancement

#1093 Update Project Dashboard Samples Counts
  app/views/shared/project/_row.html.erb
Labels: ready for review

#1094 Compact samplesheet form data
  .github/workflows/ruby.yml
  app/assets/tailwind/application.css
  app/components/layout_component.html.erb
  app/components/samples/table_component.rb
  app/javascript/controllers/editable_cell_controller.js
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/views/groups/show.html.erb
Labels: bug

#1081 Standardize border radius to rounded-lg across all components
  app/assets/tailwind/application.css
  app/components/activities/dialogs/activity_list_dialog_component.html.erb
  app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb
  app/components/advanced_search/condition.html.erb
  app/components/advanced_search_component.html.erb
  app/components/attachments/dialogs/delete_attachment_component.html.erb
  app/components/confirmation_component.html.erb
  app/components/pagination_component.html.erb
  app/components/token_component.html.erb
  app/components/viral/avatar_component.rb
  app/components/viral/card_component.rb
  app/components/viral/dialog/header_component.rb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dropdown_component.rb
  app/components/viral/form/datepicker_component.rb
  app/components/viral/form/prefixed/boolean_component.html.erb
  app/components/viral/form/prefixed/select2_component.html.erb
  app/components/viral/form/prefixed/select_component.html.erb
  app/components/viral/form/prefixed/text_input_component.html.erb
  app/components/viral/pagy/pagination_component.html.erb
  app/components/viral/select2_component.html.erb
  app/components/viral/select2_option_component.rb
  app/components/viral/sortable_list/list_component.rb
  app/views/data_exports/_new_analysis_export_dialog.html.erb
  app/views/data_exports/_new_linelist_export_dialog.html.erb
  app/views/data_exports/_new_sample_export_dialog.html.erb
  app/views/data_exports/_new_single_analysis_export_dialog.html.erb
  app/views/groups/_edit_advanced_path.html.erb
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/attachments/index.html.erb
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/bots/index.html.erb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/workflow_executions/_edit_dialog.html.erb
  app/views/groups/workflow_executions/_params.html.erb
  app/views/projects/_change_path.html.erb
  app/views/projects/_transfer_form.html.erb
  app/views/projects/attachments/index.html.erb
  app/views/projects/automated_workflow_executions/index.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/index.html.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  app/views/projects/workflow_executions/_edit_dialog.html.erb
  app/views/projects/workflow_executions/_params.html.erb
  app/views/shared/loading/_history.html.erb
  app/views/shared/metadata_templates/_edit_template_dialog.html.erb
  app/views/shared/metadata_templates/_new_template_dialog.html.erb
  app/views/shared/workflow_executions/_destroy_multiple_confirmation_dialog.html.erb
  app/views/workflow_executions/_edit_dialog.html.erb
  app/views/workflow_executions/_params.html.erb
  app/views/workflow_executions/file_selector/_file_selector_dialog.html.erb
  test/components/previews/selection_preview/within_a_table.html.erb
Labels: ready for review

#1097 Fix: Slow Samples table paging while viewing metadata
  Gemfile.lock
  app/components/samples/table_component.rb
  app/javascript/controllers/editable_cell_controller.js
  app/javascript/controllers/viral/dropdown_controller.js
  app/views/projects/samples/attachments/create.turbo_stream.erb
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
Labels: bug

#1101 style: update clipboard tooltip styling for improved visibility and a…
  app/components/clipboard_component.html.erb
Labels: accessibility

#1102 Fix: Sidebar overlay focus transfer on expand via keyboard
  app/components/layout/sidebar_component.html.erb
  app/components/layout_component.html.erb
  app/javascript/controllers/layout_controller.js
Labels: ready for review, accessibility

#1107 Nextflow: JSON form submission
  app/javascript/controllers/form/json_submission_controller.js
  app/javascript/controllers/nextflow/samplesheet_controller.js
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review
