Repository phac-nml/irida-next, pull requests merged in 2025-03, with the labels that each got.

#950 add metadata parsing to batch sample import service
  app/services/samples/batch_file_import_service.rb
  test/fixtures/files/batch_sample_import_with_metadata_valid.csv
  test/fixtures/files/batch_sample_import_with_metadata_with_empty.csv
  test/services/samples/batch_file_import_service_test.rb
Labels: enhancement, ready for review

#970 Fix: Workflow Executions stuck on completing when sample is deleted during execution
  app/models/samples_workflow_execution.rb
  app/services/workflow_executions/completion_service.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/services/workflow_executions/completion_service_test.rb
Labels: bug

#953 Progress Bars
  Procfile.dev
  app/components/viral/dialog/header_component.html.erb
  app/controllers/projects/samples/transfers_controller.rb
  app/jobs/samples/clone_job.rb
  app/jobs/samples/metadata_import_job.rb
  app/jobs/samples/transfer_job.rb
  app/jobs/workflow_execution_status_job.rb
  app/models/namespaces/project_namespace.rb
  app/services/base_service.rb
  app/services/samples/clone_service.rb
  app/services/samples/metadata/file_import_service.rb
  app/services/samples/transfer_service.rb
  app/views/groups/samples/metadata/file_imports/create.turbo_stream.erb
  app/views/groups/samples/metadata/file_imports/new.turbo_stream.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/clones/create.turbo_stream.erb
  app/views/projects/samples/clones/new.turbo_stream.erb
  app/views/projects/samples/metadata/_form.html.erb
  app/views/projects/samples/metadata/file_imports/create.turbo_stream.erb
  app/views/projects/samples/metadata/file_imports/new.turbo_stream.erb
  app/views/projects/samples/shared/_success.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  app/views/projects/samples/transfers/create.turbo_stream.erb
  app/views/projects/samples/transfers/new.turbo_stream.erb
  app/views/shared/_progress_bar.html.erb
  app/views/shared/samples/metadata/file_imports/_dialog.html.erb
  app/views/shared/samples/metadata/file_imports/_success.html.erb
  config/initializers/turbo_streams.rb
  config/locales/en.yml
  config/locales/fr.yml
  db/seeds.rb
  test/controllers/groups/samples/metadata/file_import_controller_test.rb
  test/controllers/projects/samples/clones_controller_test.rb
  test/controllers/projects/samples/metadata/file_import_controller_test.rb
  test/controllers/projects/samples/transfers_controller_test.rb
  test/models/namespaces/project_namespace_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#967 Nextflow - Metadata Headers
  app/components/nextflow/samplesheet/header_component.html.erb
  app/components/viral/form/prefixed/text_input_component.html.erb
  app/components/viral/form/prefixed/text_input_component.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  db/seeds.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/files/s.mlst.json
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review

#980 dependency: Added hotwire-spark
  Gemfile
  Gemfile.lock
  config/environments/development.rb
Labels: dependencies

#949 feat: Add preview to workflow execution files
  app/assets/icons/heroicons/download.svg
  app/controllers/attachments_controller.rb
  app/controllers/concerns/spreadsheet_parser.rb
  app/controllers/workflow_executions_controller.rb
  app/helpers/layout_helper.rb
  app/helpers/pill_color_helper.rb
  app/javascript/controllers/copy_controller.js
  app/models/attachment.rb
  app/views/attachments/csv_preview.html.erb
  app/views/attachments/image_preview.html.erb
  app/views/attachments/json_preview.html.erb
  app/views/attachments/spreadsheet_preview.html.erb
  app/views/attachments/text_preview.html.erb
  app/views/attachments/tsv_preview.html.erb
  app/views/layouts/attachment.html.erb
  app/views/workflow_executions/_attachment.html.erb
  app/views/workflow_executions/_files.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  config/routes/attachments.rb
  db/seeds.rb
  test/controllers/attachment_controller_test.rb
  test/controllers/concerns/spreadsheet_parser_test.rb
  test/fixtures/active_storage/attachments.yml
  test/fixtures/active_storage/blobs.yml
  test/fixtures/attachments.yml
  test/fixtures/files/attachment_preview.csv
  test/fixtures/files/attachment_preview.json
  test/fixtures/files/attachment_preview.tsv
  test/fixtures/files/attachment_preview.txt
  test/fixtures/files/attachment_preview.webp
  test/fixtures/files/attachment_preview.xlsx
  test/fixtures/files/blob_outputs/normal/testCSV.csv
  test/fixtures/files/blob_outputs/normal/testExcel.xlsx
  test/fixtures/files/blob_outputs/normal/testImage.webp
  test/fixtures/files/blob_outputs/normal/testJson.json
  test/fixtures/files/blob_outputs/normal/testTSV.tsv
  test/fixtures/files/spreadsheet_helper_test/empty.csv
  test/fixtures/files/spreadsheet_helper_test/good.xlsx
  test/fixtures/files/spreadsheet_helper_test/good_csv.csv
  test/fixtures/files/spreadsheet_helper_test/incorrect_cols.csv
  test/fixtures/files/spreadsheet_helper_test/missing_headers.csv
  test/fixtures/files/spreadsheet_helper_test/missing_headers.xlsx
  test/fixtures/files/spreadsheet_helper_test/missing_rows.csv
  test/fixtures/files/spreadsheet_helper_test/only_headers.csv
  test/fixtures/files/spreadsheet_helper_test/only_headers.xlsx
  test/fixtures/files/spreadsheet_helper_test/unsupported.txt
  test/helpers/layout_helper_test.rb
  test/models/attachment_test.rb
  test/system/attachments_test.rb
  test/system/data_exports_test.rb
Labels: enhancement

#991 Samples table speedup
  app/components/samples/editable_cell.html.erb
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/javascript/controllers/inline_edit_controller.js
  app/javascript/controllers/projects/samples/metadata/editable_cell_controller.js
  app/views/groups/samples/_table.html.erb
  app/views/projects/samples/_table.html.erb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#992 Don't require project field when importing samples into project
  app/controllers/concerns/sample_spreadsheet_import_actions.rb
  app/controllers/groups/samples/spreadsheet_imports_controller.rb
  app/controllers/projects/samples/spreadsheet_imports_controller.rb
  app/services/samples/batch_file_import_service.rb
  test/controllers/groups/samples/spreadsheet_import_controller_test.rb
  test/controllers/projects/samples/spreadsheet_import_controller_test.rb
  test/fixtures/files/batch_sample_import/group/invalid_blank_line.csv
  test/fixtures/files/batch_sample_import/group/invalid_missing_puid.csv
  test/fixtures/files/batch_sample_import/group/invalid_project.csv
  test/fixtures/files/batch_sample_import/group/invalid_sample_dup_in_file.csv
  test/fixtures/files/batch_sample_import/group/invalid_sample_exists.csv
  test/fixtures/files/batch_sample_import/group/invalid_short_sample_name.csv
  test/fixtures/files/batch_sample_import/group/valid.csv
  test/fixtures/files/batch_sample_import/group/with_metadata_valid.csv
  test/fixtures/files/batch_sample_import/group/with_metadata_with_empty.csv
  test/fixtures/files/batch_sample_import/project/invalid_blank_line.csv
  test/fixtures/files/batch_sample_import/project/invalid_sample_dup_in_file.csv
  test/fixtures/files/batch_sample_import/project/invalid_sample_exists.csv
  test/fixtures/files/batch_sample_import/project/invalid_short_sample_name.csv
  test/fixtures/files/batch_sample_import/project/valid.csv
  test/fixtures/files/batch_sample_import/project/with_metadata_valid.csv
  test/fixtures/files/batch_sample_import/project/with_metadata_with_empty.csv
  test/services/samples/group_batch_sample_import_service_test.rb
  test/services/samples/project_batch_sample_import_service_test.rb
Labels: enhancement, ready for review
