Repository phac-nml/irida-next, pull requests merged in 2025-04, with the labels that each got.

#1002 Expanded w3c validation
  app/assets/icons/heroicons/folder_open.svg
  app/components/attachments/dialogs/new_attachment_component.html.erb
  app/components/history_component.html.erb
  app/components/list_input_component.html.erb
  app/components/nextflow_component.html.erb
  app/components/viral/page_header_component.html.erb
  app/components/viral/page_header_component.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/javascript/utilities/form.js
  app/models/concerns/file_selector.rb
  app/views/attachments/image_preview.html.erb
  app/views/devise/sessions/new_with_providers.html.erb
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/members/_access_level.html.erb
  app/views/layouts/attachment.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/members/_access_level.html.erb
  app/views/projects/samples/attachments/_form.html.erb
  test/components/previews/viral_form_prefixed_select2_component_preview/default.html.erb
  test/components/previews/viral_page_header_component_preview/with_avatar.html.erb
  test/components/previews/viral_page_header_component_preview/with_icon.html.erb
  test/components/previews/viral_select2_component_preview/default.html.erb
  test/fixtures/files/tyrell.svg
  test/system/groups/attachments_test.rb
  test/system/projects/attachments_test.rb
  test/system/projects/samples/attachments_test.rb
  test/test_helpers/axe_helpers.rb
Labels: ready for review, accessibility

#1010 Bug: Samplesheet Default PE file selection
  app/models/concerns/file_selector.rb
Labels: bug, ready for review

#1014 Fix issue with namespace tree render dark border for namespace-entry
  app/assets/tailwind/application.css
Labels: bug

#978 Workflow Executions: Multiple Delete
  app/controllers/concerns/workflow_execution_actions.rb
  app/controllers/projects/workflow_executions_controller.rb
  app/controllers/workflow_executions_controller.rb
  app/javascript/controllers/infinite_scroll_controller.js
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/services/workflow_executions/destroy_service.rb
  app/views/data_exports/_list_workflow_execution.html.erb
  app/views/data_exports/list.turbo_stream.erb
  app/views/groups/workflow_executions/index.html.erb
  app/views/projects/workflow_executions/destroy_multiple.turbo_stream.erb
  app/views/projects/workflow_executions/index.html.erb
  app/views/projects/workflow_executions/list.turbo_stream.erb
  app/views/shared/workflow_executions/_destroy_multiple_confirmation_dialog.html.erb
  app/views/shared/workflow_executions/_list_workflow_execution.html.erb
  app/views/workflow_executions/destroy_multiple.turbo_stream.erb
  app/views/workflow_executions/index.html.erb
  app/views/workflow_executions/list.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  config/routes/workflow_executions.rb
  db/seeds.rb
  test/components/workflow_execution_activity_component_test.rb
  test/controllers/projects/workflow_executions_controller_test.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/workflow_executions.yml
  test/policies/group_policy_test.rb
  test/services/workflow_executions/destroy_service_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: ready for review

#1011 Update tables accessibility
  app/components/attachments/table_component.html.erb
  app/components/attachments/table_component.rb
  app/components/members/table_component.html.erb
  app/components/metadata_templates/table_component.html.erb
  app/components/viral/data_table/column_component.rb
  app/components/viral/data_table_component.html.erb
  app/components/workflow_executions/table_component.html.erb
Labels: accessibility

#1020 Authentication Language Selection
  app/assets/icons/heroicons/language.svg
  app/assets/tailwind/application.css
  app/controllers/application_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new_with_providers.html.erb
  app/views/devise/shared/_form.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/devise.html.erb
  app/views/profiles/preferences/_locale_form.html.erb
  app/views/shared/_dark_mode_check.html.erb
  config/locales/devise.en.yml
  config/locales/devise.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  test/models/user_test.rb
  test/system/profile_test.rb
Labels: accessibility

#1013 Nextflow: Improve File Selector Accessbility
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/views/workflow_executions/file_selector/_file_selector_dialog.html.erb
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review, accessibility

#1019 Refactor Spinner Component ID
  app/components/nextflow_component.html.erb
  app/components/spinner_component.html.erb
  app/components/spinner_component.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  test/components/spinner_component_test.rb
  test/system/groups/metadata_templates_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/projects/samples_test.rb
  test/system/workflow_executions/submissions_test.rb
Labels: ready for review

#1018 Table sort accessibility
  app/components/attachments/table_component.html.erb
  app/components/attachments/table_component.rb
  app/components/data_exports/table_component.html.erb
  app/components/data_exports/table_component.rb
  app/components/groups/table_component.html.erb
  app/components/layout_component.html.erb
  app/components/members/table_component.html.erb
  app/components/metadata_templates/table_component.html.erb
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  app/components/viral/data_table_component.rb
  app/components/workflow_executions/table_component.html.erb
  app/components/workflow_executions/table_component.rb
  app/helpers/sorting_helper.rb
  app/javascript/controllers/editable_cell_controller.js
  test/helpers/sorting_helper_test.rb
  test/system/dashboard/projects_test.rb
  test/system/data_exports_test.rb
  test/system/groups/bots_test.rb
  test/system/groups/samples_test.rb
  test/system/groups/workflow_executions_test.rb
  test/system/profile_test.rb
  test/system/projects/automated_workflow_executions_test.rb
  test/system/projects/bots_test.rb
  test/system/projects/samples_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: accessibility

#1043 Updated sample metadata template dropdown to act like a normal dropdown
  app/javascript/controllers/metadata_template_dd_controller.js
  app/views/shared/samples/_metadata_template_dropdown.html.erb
  app/views/shared/samples/_metadata_template_item.html.erb
  app/views/shared/samples/_metadata_templates_list.html.erb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#1030 Enhanced project dropdown
  app/assets/tailwind/application.css
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/puid_component.html.erb
  app/components/puid_component.rb
  app/components/viral/form/prefixed/select2_component.html.erb
  app/components/viral/pill_component.rb
  app/components/viral/select2_component.html.erb
  app/components/viral/select2_option_component.rb
  app/javascript/controllers/infinite_scroll_controller.js
  app/javascript/controllers/layout_controller.js
  app/javascript/controllers/spreadsheet_import_controller.js
  app/javascript/controllers/viral/select2_controller.js
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/_form_fields.html.erb
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/profiles/personal_access_tokens/_form.html.erb
  app/views/profiles/preferences/show.html.erb
  app/views/projects/_project_namespace_fields.html.erb
  app/views/projects/_transfer_form.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/samples/_list_sample.html.erb
  app/views/projects/samples/clones/_dialog.html.erb
  app/views/projects/samples/deletions/_new_multiple_deletions_dialog.html.erb
  app/views/projects/samples/transfers/_dialog.html.erb
  app/views/shared/samples/metadata/file_imports/_dialog.html.erb
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  test/components/previews/puid_component_preview.rb
  test/components/previews/puid_component_preview/no_clipboard.html.erb
  test/components/previews/viral_form_prefixed_select2_component_preview/default.html.erb
  test/components/previews/viral_select2_component_preview/default.html.erb
  test/components/puid_component_test.rb
  test/components/viral/form/prefixed/select2_component_test.rb
  test/components/viral/select2_component_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/group_links_test.rb
  test/system/groups/members_test.rb
  test/system/groups_test.rb
  test/system/projects/group_links_test.rb
  test/system/projects/members_test.rb
  test/system/projects/samples_test.rb
  test/system/projects/transfer_test.rb
  test/system/projects_test.rb
Labels: enhancement

#1048 Fix: Pagy OverflowError
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  config/initializers/pagy.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: bug

#1050 Fix: Batch Sample Import Rebase
  app/javascript/controllers/spreadsheet_import_controller.js
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review
