Repository phac-nml/irida-next, pull requests merged in 2025-02, with the labels that each got.

#931 Nextflow Samplesheet: Bug Fixes (submission and table load)
  app/components/nextflow_component.html.erb
  app/javascript/controllers/nextflow/samplesheet_controller.js
Labels: bug, ready for review

#923 UI: Create Metadata Template
  app/components/metadata_templates/table_component.html.erb
  app/controllers/concerns/metadata_template_actions.rb
  app/controllers/projects/metadata_templates_controller.rb
  app/controllers/projects/samples/metadata/fields_controller.rb
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/services/metadata_templates/create_service.rb
  app/views/groups/metadata_templates/create.turbo_stream.erb
  app/views/groups/metadata_templates/destroy.turbo_stream.erb
  app/views/groups/metadata_templates/new.turbo_stream.erb
  app/views/projects/metadata_templates/create.turbo_stream.erb
  app/views/projects/metadata_templates/destroy.turbo_stream.erb
  app/views/projects/metadata_templates/new.turbo_stream.erb
  app/views/shared/metadata_templates/_create.turbo_stream.erb
  app/views/shared/metadata_templates/_header.html.erb
  app/views/shared/metadata_templates/_new_template_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/metadata_templates/create_service_test.rb
  test/system/groups/metadata_templates_test.rb
  test/system/projects/metadata_templates_test.rb
Labels: enhancement

#924 UI: Edit Metadata Template
  app/components/metadata_templates/table_component.html.erb
  app/components/metadata_templates/table_component.rb
  app/controllers/concerns/metadata_template_actions.rb
  app/controllers/groups/metadata_templates_controller.rb
  app/controllers/projects/metadata_templates_controller.rb
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/views/groups/metadata_templates/edit.turbo_stream.erb
  app/views/groups/metadata_templates/update.turbo_stream.erb
  app/views/projects/metadata_templates/edit.turbo_stream.erb
  app/views/projects/metadata_templates/update.turbo_stream.erb
  app/views/shared/metadata_templates/_edit_template_dialog.html.erb
  app/views/shared/metadata_templates/_update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/metadata_templates.yml
  test/system/groups/metadata_templates_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#914 Metadata Templates Selection UI
  app/controllers/concerns/metadata.rb
  app/controllers/concerns/metadata_template_actions.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples_controller.rb
  app/controllers/workflow_executions/submissions_controller.rb
  app/models/namespace.rb
  app/models/project.rb
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/views/groups/samples/_table_filter.html.erb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/_table_filter.html.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/shared/_metadata_toggle.html.erb
  app/views/shared/samples/_metadata_template_dropdown.html.erb
  app/views/shared/samples/_metadata_templates_list.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/group.rb
  config/routes/project.rb
  test/controllers/concerns/metadata_concern_test.rb
  test/controllers/concerns/metadata_templates_actions_concern_test.rb
  test/controllers/groups/metadata_templates_controller_test.rb
  test/controllers/groups/samples_controller_test.rb
  test/controllers/projects/metadata_templates_controller_test.rb
  test/controllers/projects/samples_controller_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#944 Fix advanced search dialog triggering close when auto-completing input
  app/javascript/controllers/advanced_search_controller.js
Labels: bug

#943 Fix: Nextflow Metadata Fields
  app/controllers/workflow_executions/submissions_controller.rb
  test/controllers/workflow_executions/submission_controller_test.rb
Labels: bug, ready for review

#942 Graphql: Pipeline updates
  app/graphql/schema.graphql
  app/graphql/types/pipeline_type.rb
  docs-site/docs/extend/graphql_workflow_submission.md
  test/graphql/pipeline_query_test.rb
  test/graphql/pipelines_query_test.rb
Labels: documentation, graphql

#941 Metadata Template Field Selection on Linelist Export
  app/components/viral/sortable_lists_component.html.erb
  app/components/viral/sortable_lists_component.rb
  app/controllers/concerns/metadata.rb
  app/controllers/concerns/metadata_template_actions.rb
  app/controllers/data_exports_controller.rb
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/views/data_exports/_new_linelist_export_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/concerns/metadata_templates_actions_concern_test.rb
  test/fixtures/metadata_templates.yml
  test/policies/metadata_templates_policy_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement

#897 Batch sample import service
  app/jobs/samples/batch_sample_import_job.rb
  app/policies/group_policy.rb
  app/policies/namespaces/project_namespace_policy.rb
  app/services/base_spreadsheet_import_service.rb
  app/services/samples/batch_file_import_service.rb
  app/services/samples/metadata/file_import_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/files/batch_sample_import_invalid_blank_line.csv
  test/fixtures/files/batch_sample_import_invalid_missing_puid.csv
  test/fixtures/files/batch_sample_import_invalid_project.csv
  test/fixtures/files/batch_sample_import_invalid_sample_dup_in_file.csv
  test/fixtures/files/batch_sample_import_invalid_sample_exists.csv
  test/fixtures/files/batch_sample_import_invalid_short_sample_name.csv
  test/fixtures/files/batch_sample_import_valid.csv
  test/fixtures/files/metadata/empty.csv
  test/policies/group_policy_test.rb
  test/policies/namespaces/project_namespace_policy_test.rb
  test/services/samples/batch_file_import_service_test.rb
  test/services/samples/metadata/file_import_service_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#951 Fix: Samplesheet Attachment format validation for non fastq files
  .gitignore
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/validators/workflow_execution_samplesheet_params_validator.rb
  config/initializers/pipelines.rb
  config/pipelines/test.json
  lib/irida/pipelines.rb
  test/fixtures/samples_workflow_executions.yml
  test/fixtures/workflow_executions.yml
  test/graphql/pipelines_query_test.rb
  test/lib/irida/pipelines_overrides_test.rb
  test/lib/irida/pipelines_schema_test.rb
  test/lib/irida/pipelines_test.rb
  test/models/samples_workflow_executions_test.rb
Labels: bug

#954 Fix: Allow template fields that are not within the sample metadata to be exported
  app/components/viral/sortable_list/list_component.html.erb
  app/components/viral/sortable_list/list_item_component.html.erb
  app/components/viral/sortable_list/list_item_component.rb
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/views/data_exports/_new_linelist_export_dialog.html.erb
Labels: enhancement

#956 Fix flakey workflow job tests
  test/jobs/workflow_execution_cancelation_job_test.rb
  test/jobs/workflow_execution_status_job_test.rb
  test/jobs/workflow_execution_submission_job_test.rb
Labels: ready for review

#965 Fix: Nextflow Samplesheet File Cell Pattern Recognition
  app/components/nextflow/samplesheet_component.rb
  app/models/concerns/file_selector.rb
Labels: bug
