Repository phac-nml/irida-next, pull requests merged in 2025-09, with the labels that each got.

#1218 Accessibility: Profile main settings
  app/views/profiles/_form.html.erb
Labels: accessibility

#1213 Updated aria labels for treegrid row component
  app/helpers/namespace_row_helper.rb
  app/views/dashboard/groups/group.turbo_stream.erb
  app/views/dashboard/groups/index.html.erb
  app/views/dashboard/projects/index.html.erb
  app/views/groups/_shared_namespaces.html.erb
  app/views/groups/_subgroups_and_projects.html.erb
  app/views/groups/subgroups/subgroup.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibility

#1189 Added exception handling to DataExports CreateJob
  app/jobs/data_exports/create_job.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/jobs/data_exports/create_job_test.rb
Labels: bug, ready for review

#1133 Accessibility: Sortable Lists Enhancements
  app/assets/tailwind/application.css
  app/components/viral/sortable_list/list_component.html.erb
  app/components/viral/sortable_list/list_component.rb
  app/components/viral/sortable_list/list_item_component.html.erb
  app/components/viral/sortable_list/list_item_component.rb
  app/components/viral/sortable_lists_component.html.erb
  app/components/viral/sortable_lists_component.rb
  app/javascript/controllers/metadata/file_import_controller.js
  app/javascript/controllers/viral/sortable_lists/two_lists_selection_controller.js
  app/views/data_exports/_new_linelist_export_dialog.html.erb
  app/views/data_exports/_new_sample_export_dialog.html.erb
  app/views/shared/metadata_templates/_edit_template_dialog.html.erb
  app/views/shared/metadata_templates/_new_template_dialog.html.erb
  app/views/shared/samples/metadata/file_imports/_dialog.html.erb
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/workflow_executions/submission_controller_test.rb
  test/fixtures/groups.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/samples.yml
  test/models/group_test.rb
  test/system/data_exports_test.rb
  test/system/groups/metadata_templates_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/metadata_templates_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review, accessibility

#1220 Fix: Editable Cell focus, connection, and clearing
  app/components/samples/editable_cell.html.erb
  app/components/samples/editable_cell.rb
  app/controllers/samples/metadata_controller.rb
  app/javascript/controllers/editable_cell_controller.js
  app/services/samples/metadata/fields/update_service.rb
Labels: bug, ready for review, accessibility

#1219 Samples Attachments Reflow
  app/views/projects/samples/attachments/_table.html.erb
Labels: ready for review, accessibility

#1214 Accessibility: Upload files
  app/components/attachments/dialogs/new_attachment_component.html.erb
  app/javascript/controllers/attachment_upload_controller.js
  app/javascript/controllers/file_upload_controller.js
  app/views/projects/samples/attachments/_form.html.erb
  app/views/shared/samples/metadata/file_imports/_dialog.html.erb
  app/views/shared/samples/spreadsheet_imports/_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibility

#1225 Accessibility: Metadata template dropdown
  app/views/shared/samples/_metadata_template_dropdown.html.erb
  app/views/shared/samples/_metadata_template_item.html.erb
  app/views/shared/samples/_metadata_templates_list.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibility

#1228 Platform table checkbox cleanup
  app/components/attachments/table_component.html.erb
  app/components/samples/table_component.html.erb
  app/components/workflow_executions/table_component.html.erb
  app/javascript/controllers/projects/samples/attachments/files_controller.js
  app/javascript/controllers/projects/samples/metadata/delete_listing_controller.js
  app/views/projects/samples/metadata/_table.html.erb
  embedded_gems/pathogen/app/components/pathogen/form/checkbox.rb
  embedded_gems/pathogen/app/components/pathogen/form/checkbox_styles.rb
  embedded_gems/pathogen/app/components/pathogen/form/form_option_extractor.rb
  test/components/pathogen/checkbox_test.rb
  test/components/previews/pathogen/form/checkbox_preview.rb
  test/components/previews/pathogen/form/checkbox_preview/form_builder.html.erb
  test/components/previews/pathogen/form/checkbox_preview/form_group.html.erb
  test/components/previews/pathogen/form/checkbox_preview/interactive_group.html.erb
  test/components/previews/pathogen/form/checkbox_preview/multiple_checkboxes.html.erb
  test/components/previews/pathogen/form/checkbox_preview/terms_and_conditions.html.erb
  test/components/previews/pathogen/form/checkbox_preview/user_preferences.html.erb
  test/components/previews/pathogen/form/checkbox_preview/with_aria_labelledby.html.erb
Labels: accessibility

#1232 Fix aria-label for workflow execution checkbox to use presence method
  app/components/workflow_executions/table_component.html.erb
Labels: bug

#1240 Fix: Button/search bar reflow followup
  app/views/dashboard/groups/index.html.erb
  app/views/dashboard/projects/index.html.erb
  app/views/data_exports/show.html.erb
  app/views/groups/bots/index.html.erb
  app/views/groups/samples/index.html.erb
  app/views/groups/show.html.erb
  app/views/projects/automated_workflow_executions/index.html.erb
  app/views/projects/bots/index.html.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/shared/metadata_templates/_header.html.erb
  embedded_gems/pathogen/app/components/pathogen/tabs_panel.html.erb
Labels: ready for review, accessibility

#1237 Metadata template form accessibility
  app/components/metadata_templates/table_component.html.erb
  app/controllers/concerns/metadata_template_actions.rb
  app/views/shared/metadata_templates/_create.turbo_stream.erb
  app/views/shared/metadata_templates/_edit_template_dialog.html.erb
  app/views/shared/metadata_templates/_form.html.erb
  app/views/shared/metadata_templates/_new_template_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/groups/metadata_templates_test.rb
  test/system/projects/metadata_templates_test.rb
Labels: accessibility

#1238 Fix: Scrolling on delete sample metadata/file dialogs and Edit Workflow buttons
  app/views/projects/samples/attachments/deletions/_modal.html.erb
  app/views/projects/samples/metadata/deletions/_modal.html.erb
  app/views/projects/workflow_executions/_edit_dialog.html.erb
  app/views/workflow_executions/_edit_dialog.html.erb
Labels: ready for review, accessibility

#1236 Clean up dark mode error visibility for reset password
  app/javascript/controllers/email_input_controller.js
  app/views/devise/passwords/new.html.erb
Labels: accessibility

#1255 Table PUIDs
  app/components/attachments/table_component.html.erb
  app/components/samples/table_component.html.erb
  app/components/workflow_executions/table_component.html.erb
  app/helpers/style_helper.rb
  app/views/projects/samples/metadata/_table.html.erb
Labels: enhancement

#1246 Localize local_time
  app/javascript/application.js
  app/views/layouts/lookbook.html.erb
  app/views/layouts/partials/_head.html.erb
  app/views/shared/_local_time.html.erb
  config/i18n-tasks.yml
  config/locales/local_time.fr.yml
  test/components/previews/viral_data_table_component_preview/default.html.erb
  test/components/previews/viral_data_table_component_preview/overflow_x.html.erb
  test/components/viral/system/data_table_component_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#1258 Accessibility: Search Field Component
  app/components/search_component.html.erb
  app/components/search_field_component.html.erb
  app/views/groups/samples/_table_filter.html.erb
  app/views/projects/samples/_table_filter.html.erb
Labels: accessibility

#1256 Implements Pathogen form builder labels
  app/assets/tailwind/application.css
  app/javascript/controllers/projects/samples/metadata/create_controller.js
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/_form_fields.html.erb
  app/views/groups/group_links/_form.html.erb
  app/views/groups/members/_form.html.erb
  app/views/projects/_project_namespace_fields.html.erb
  app/views/projects/_transfer_form.html.erb
  app/views/projects/group_links/_form.html.erb
  app/views/projects/members/_form.html.erb
  app/views/projects/samples/metadata/_form.html.erb
  app/views/samples/clones/_dialog.html.erb
  app/views/samples/transfers/_dialog.html.erb
  app/views/shared/personal_access_tokens/_form_fields.html.erb
  config/i18n-tasks.yml
  embedded_gems/pathogen/config/locales/en.yml
  embedded_gems/pathogen/config/locales/fr.yml
  embedded_gems/pathogen/lib/pathogen/form_builders/pathogen_form_builder.rb
  test/system/projects/samples/metadata_test.rb
Labels: accessibility

#1262 Update AdvancedSearch component to have visible labels
  app/components/advanced_search/condition.html.erb
  app/components/advanced_search/value.html.erb
  app/components/advanced_search_component.html.erb
  app/components/list_input_component.html.erb
  app/components/list_input_component.rb
Labels: ready for review, accessibility
