Repository phac-nml/irida-next, pull requests merged in 2025-01, with the labels that each got.

#869 Refactor: Project Samples Test
  test/fixtures/samples.yml
  test/system/projects/samples_test.rb
Labels: ready for review

#878 Update dependency azure-storage-blob to azure-blob
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/services/workflow_executions/preparation_service.rb
  config/storage.yml
  lib/active_storage/service/azure_storage_service.rb
  lib/azure/storage/blob/default.rb
  lib/azure/storage/common/default.rb
Labels: ready for review, dependencies

#864 Enhancement: Edit line list metadata in place
  app/components/nextflow/samplesheet/metadata_cell_component.rb
  app/components/samples/editable_cell.html.erb
  app/components/samples/editable_cell.rb
  app/components/samples/table_component.html.erb
  app/controllers/projects/samples/metadata/fields_controller.rb
  app/javascript/controllers/inline_edit_controller.js
  app/models/sample.rb
  app/services/samples/metadata/update_service.rb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/index.html.erb
  app/views/shared/_flash.html.erb
  app/views/shared/samples/_timestamp_input.html.erb
  app/views/shared/samples/metadata/fields/_editable_field_cell.html.erb
  app/views/shared/samples/metadata/fields/_editing_field_cell.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes/project.rb
  test/controllers/projects/samples/metadata/fields/fields_controller_test.rb
  test/models/sample_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review

#862 Update: Group samples count calculation should include shared groups and projects
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/controllers/groups/samples_controller.rb
  app/models/group.rb
  test/controllers/concerns/project_share_actions_concern_test.rb
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespace_group_links.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/models/group_test.rb
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
Labels: ready for review

#890 Workflow Execution logidze
  db/migrate/20250109162252_add_logidze_to_workflow_executions.rb
  db/schema.rb
  db/triggers/logidze_on_workflow_executions_v01.sql
  test/services/workflow_executions/cancel_service_test.rb
  test/services/workflow_executions/completion_service_test.rb
  test/services/workflow_executions/create_service_test.rb
  test/services/workflow_executions/preparation_service_test.rb
Labels: database

#892 Quality of Life: Enable web console as a development option
  app/controllers/console_controller.rb
  app/views/console/show.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/groups.html.erb
  app/views/layouts/profiles.html.erb
  app/views/layouts/projects.html.erb
  config/environments/development.rb
  config/routes/development.rb
  docs-site/docs/configuration/options.md
Labels: ready for review

#838 Graphql: Submit Workflow Execution
  app/controllers/workflow_executions_controller.rb
  app/graphql/mutations/submit_workflow_execution.rb
  app/graphql/schema.graphql
  app/graphql/types/mutation_type.rb
  app/models/samples_workflow_execution.rb
  app/models/workflow_execution.rb
  app/validators/workflow_execution_samplesheet_params_validator.rb
  db/seeds.rb
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/samples_workflow_executions.yml
  test/graphql/submit_workflow_execution_mutation_test.rb
  test/models/samples_workflow_executions_test.rb
  test/services/workflow_executions/create_service_test.rb
Labels: ready for review, graphql

#893 UI: Edit workflow execution
  app/components/workflow_executions/table_component.html.erb
  app/controllers/concerns/workflow_execution_actions.rb
  app/policies/workflow_execution_policy.rb
  app/views/projects/workflow_executions/_edit_dialog.html.erb
  app/views/projects/workflow_executions/_summary.html.erb
  app/views/projects/workflow_executions/_table.html.erb
  app/views/projects/workflow_executions/edit.turbo_stream.erb
  app/views/projects/workflow_executions/show.html.erb
  app/views/projects/workflow_executions/update.turbo_stream.erb
  app/views/workflow_executions/_edit_dialog.html.erb
  app/views/workflow_executions/_summary.html.erb
  app/views/workflow_executions/_table.html.erb
  app/views/workflow_executions/edit.turbo_stream.erb
  app/views/workflow_executions/show.html.erb
  app/views/workflow_executions/update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/policies/workflow_execution_policy_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement

#919 Samples Table loading overlay
  app/components/samples/table_component.html.erb
  app/components/samples/table_component.rb
  app/components/spinner_component.html.erb
  app/views/groups/samples/search.turbo_stream.erb
  app/views/projects/samples/search.turbo_stream.erb
  app/views/shared/loading/_spinner.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement
