Repository phac-nml/irida-next, pull requests merged in 2025-08, with the labels that each got.

#1141 Advanced search accessibility
  app/components/advanced_search/condition.html.erb
  app/components/advanced_search/value.html.erb
  app/components/advanced_search_component.html.erb
  app/components/list_input_component.html.erb
  app/components/list_input_component.rb
  app/components/viral/base_component.rb
  app/javascript/controllers/advanced_search_controller.js
  app/javascript/controllers/viral/dialog_controller.js
  app/validators/advanced_search_group_validator.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/models/sample/query_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review, accessibility

#1176 Fix field error color contrast
  app/assets/tailwind/application.css
Labels: accessibility

#1172 Fix: Group edit forms accessibility
  app/assets/tailwind/application.css
  app/views/groups/_edit_advanced_path.html.erb
  app/views/groups/_edit_advanced_transfer_form.html.erb
  app/views/groups/_edit_name_and_description_form.html.erb
  app/views/groups/_form_fields.html.erb
  app/views/groups/new.html.erb
  app/views/groups/new_subgroup.html.erb
  test/system/groups_test.rb
Labels: ready for review, accessibility

#1185 A11y: Action link aria label
  app/components/attachments/table_component.html.erb
  app/components/bots/table_component.html.erb
  app/components/personal_access_tokens/table_component.html.erb
  app/components/workflow_executions/table_component.html.erb
  app/views/groups/members/_current_user_is_member.html.erb
  app/views/groups/members/_current_user_is_not_member.html.erb
  app/views/projects/automated_workflow_executions/_table.html.erb
  app/views/projects/members/_current_user_is_member.html.erb
  app/views/projects/members/_current_user_is_not_member.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/system/projects/automated_workflow_executions_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions_test.rb
Labels: accessibility

#1167 Enhance Flash Component Accessibility and Animation
  app/components/viral/flash_component.html.erb
  app/components/viral/flash_component.rb
  app/javascript/controllers/viral/flash_controller.js
  config/locales/en.yml
  config/locales/fr.yml
  test/components/viral/flash_component_test.rb
Labels: enhancement, accessibility

#1183 Fix: Invite Group create modal forms accessibility
  app/controllers/concerns/share_actions.rb
  app/services/group_links/group_link_service.rb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/group_links/create.turbo_stream.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/group_links/create.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/services/group_links/group_link_service_test.rb
Labels: accessibility

#1127 Pathogen Datepicker
  app/components/groups/table_component.html.erb
  app/components/members/table_component.html.erb
  app/components/viral/form/datepicker_component.html.erb
  app/components/viral/form/datepicker_component.rb
  app/helpers/view_helper.rb
  app/javascript/controllers/datepicker_controller.js
  app/javascript/controllers/pathogen/datepicker/calendar_controller.js
  app/javascript/controllers/pathogen/datepicker/constants.js
  app/javascript/controllers/pathogen/datepicker/input_controller.js
  app/javascript/controllers/pathogen/datepicker/utils.js
  app/views/groups/bots/_bot_modal.html.erb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/profiles/personal_access_tokens/_form.html.erb
  app/views/projects/bots/_bot_modal.html.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/members/_create_modal.html.erb
  config/i18n-tasks.yml
  config/initializers/pathogen_view_paths.rb
  config/locales/en.yml
  config/locales/fr.yml
  embedded_gems/pathogen/app/components/pathogen/datepicker.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker.rb
  embedded_gems/pathogen/app/components/pathogen/datepicker/_calendar.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker/_input_field.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker/_min_date.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker/calendar/_footer.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker/calendar/_grid.html.erb
  embedded_gems/pathogen/app/components/pathogen/datepicker/calendar/_header.html.erb
  embedded_gems/pathogen/config/locales/en.yml
  embedded_gems/pathogen/config/locales/fr.yml
  embedded_gems/pathogen/lib/pathogen/view_helper.rb
  test/components/pathogen/datepicker_test.rb
  test/components/previews/pathogen/datepicker_preview.rb
  test/components/previews/viral_form_datepicker_component_preview.rb
  test/components/previews/viral_form_datepicker_component_preview/default.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_help_text.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_label.html.erb
  test/components/previews/viral_form_datepicker_component_preview/with_placeholder.html.erb
  test/components/viral/form/datepicker_component_test.rb
  test/system/groups/group_links_test.rb
  test/system/groups/members_test.rb
  test/system/groups/samples_test.rb
  test/system/groups/workflow_executions_test.rb
  test/system/projects/group_links_test.rb
  test/system/projects/members_test.rb
  test/system/projects/samples_test.rb
Labels: enhancement, ready for review, accessibility

#1191 A11y: Dialog trigger refocus on close or disconnect/connect if open
  app/javascript/controllers/viral/dialog_controller.js
  test/components/viral/dialog_component_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review, accessibility

#1196 Accessibility: Devise layout language selection overlap
  app/views/layouts/devise.html.erb
Labels: accessibility

#1195 A11y: Dialog component reflow
  app/assets/tailwind/application.css
  app/components/activities/dialogs/activity_list_dialog_component.html.erb
  app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  app/views/groups/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/groups/group_links/_invite_group_modal.html.erb
  app/views/groups/members/_create_modal.html.erb
  app/views/groups/workflow_executions/_edit_dialog.html.erb
  app/views/projects/bots/personal_access_tokens/_generate_personal_access_token_modal.html.erb
  app/views/projects/group_links/_invite_group_modal.html.erb
  app/views/projects/members/_create_modal.html.erb
  app/views/projects/workflow_executions/_edit_dialog.html.erb
  app/views/workflow_executions/_edit_dialog.html.erb
Labels: accessibility

#1198 A11y: Dialog reflow followup
  app/assets/tailwind/application.css
  app/components/viral/dialog_component.html.erb
  app/components/viral/dialog_component.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/group_links_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/bots_test.rb
  test/system/projects/samples_test.rb
Labels: bug

#1202 A11y: Datepicker positioning followup
  Gemfile.lock
  app/javascript/controllers/pathogen/datepicker/input_controller.js
Labels: bug, accessibility

#1163 Workflow execution error refactor
  .devcontainer/devcontainer.json
  .vscode/settings.json
  app/jobs/application_job.rb
  app/jobs/workflow_execution_cancelation_job.rb
  app/jobs/workflow_execution_cleanup_job.rb
  app/jobs/workflow_execution_completion_job.rb
  app/jobs/workflow_execution_job.rb
  app/jobs/workflow_execution_preparation_job.rb
  app/jobs/workflow_execution_status_job.rb
  app/jobs/workflow_execution_submission_job.rb
  app/models/workflow_execution.rb
  app/services/workflow_executions/cancelation_service.rb
  app/services/workflow_executions/cleanup_service.rb
  app/services/workflow_executions/completion_service.rb
  app/services/workflow_executions/preparation_service.rb
  app/services/workflow_executions/status_service.rb
  app/services/workflow_executions/submission_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/workflow_executions.yml
  test/jobs/workflow_execution_cleanup_job_test.rb
  test/jobs/workflow_execution_job_test.rb
  test/jobs/workflow_execution_status_job_test.rb
  test/jobs/workflow_execution_submission_job_test.rb
  test/models/workflow_execution_test.rb
  test/services/workflow_executions/cleanup_service_test.rb
  test/services/workflow_executions/preparation_service_test.rb
  test/system/workflow_executions_test.rb
Labels: bug, ready for review

#1190 Fix: Project/Group edit reflow
  app/views/groups/_edit_advanced_path.html.erb
  app/views/projects/_change_path.html.erb
Labels: accessibility

#1186 Fix: Viral Prefixed Select2 reflow
  app/components/viral/form/prefixed/select2_component.html.erb
  app/components/viral/form/prefixed/select2_component.rb
  app/javascript/controllers/viral/select2_controller.js
  app/views/groups/_form_fields.html.erb
  app/views/projects/_project_namespace_fields.html.erb
Labels: accessibility

#1209 Accessibility: Create group/project link styling
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibility

#1194 Boolean component accessibility
  app/components/nextflow_component.html.erb
  app/components/viral/form/prefixed/boolean_component.html.erb
  app/components/viral/form/prefixed/boolean_component.rb
  app/helpers/nextflow_helper.rb
  app/javascript/controllers/selection_controller.js
  app/views/workflow_executions/file_selector/_file_selector_dialog.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/viral_form_prefixed_boolean_component_preview/default.html.erb
  test/components/previews/viral_form_prefixed_boolean_component_preview/with_false_value.html.erb
  test/components/previews/viral_form_prefixed_boolean_component_preview/with_icon.html.erb
  test/components/viral/form/prefixed/boolean_component_test.rb
Labels: accessibility
