Repository phac-nml/irida-next, pull requests merged in 2025-06, with the labels that each got.

#1105 Accessibility: Browser title update
  app/controllers/data_exports_controller.rb
  app/controllers/groups/attachments_controller.rb
  app/controllers/groups/bots_controller.rb
  app/controllers/groups/history_controller.rb
  app/controllers/groups/members_controller.rb
  app/controllers/groups/metadata_templates_controller.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/groups/workflow_executions_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/profiles/accounts_controller.rb
  app/controllers/profiles/passwords_controller.rb
  app/controllers/profiles/personal_access_tokens_controller.rb
  app/controllers/profiles/preferences_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/projects/attachments_controller.rb
  app/controllers/projects/automated_workflow_executions_controller.rb
  app/controllers/projects/bots_controller.rb
  app/controllers/projects/history_controller.rb
  app/controllers/projects/members_controller.rb
  app/controllers/projects/metadata_templates_controller.rb
  app/controllers/projects/samples_controller.rb
  app/controllers/projects/workflow_executions_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/workflow_executions_controller.rb
Labels: accessibility

#1098 Samplesheet: Refactor assigning template attributes
  app/components/nextflow/samplesheet_component.html.erb
  app/controllers/workflow_executions/metadata_controller.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
Labels: ready for review

#1112 refactor: enhance page header component layout and accessibility
  app/components/viral/page_header_component.html.erb
  test/components/viral/page_header_component_test.rb
Labels: enhancement, accessibility

#1090 Dropdown upgrades to allow fully custom button styling
  app/components/layout/sidebar_component.html.erb
  app/components/viral/breadcrumb_component.html.erb
  app/components/viral/dropdown_component.html.erb
  app/components/viral/dropdown_component.rb
  app/views/groups/samples/index.html.erb
  app/views/layouts/devise.html.erb
  app/views/projects/samples/index.html.erb
  test/components/previews/viral_dropdown_component_preview.rb
  test/components/previews/viral_dropdown_component_preview/default.html.erb
  test/components/previews/viral_dropdown_component_preview/with_caret.html.erb
  test/components/previews/viral_dropdown_component_preview/with_icon.html.erb
  test/components/previews/viral_dropdown_component_preview/with_item_icon.html.erb
  test/components/viral/system/dropdown_component_test.rb
Labels: ready for review

#1106 Enhance clipboard component with dynamic button naming and improved accessibility
  app/components/clipboard_component.html.erb
  app/components/clipboard_component.rb
  app/components/puid_component.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/previews/clipboard_component_preview/custom_content.html.erb
  test/components/previews/clipboard_component_preview/default.html.erb
Labels: enhancement, ready for review, accessibility

#1045 Fixes compatibility with vscode Code Lens
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  test/test_helpers/w3c_validation_helpers.rb
Labels: bug, ready for review

#1082 Group Samples: Delete
  app/components/activities/dialogs/activity_list_dialog_component.rb
  app/components/activities/dialogs/activity_table_listing_dialog_component.html.erb
  app/components/activities/dialogs/activity_table_listing_dialog_component.rb
  app/components/activities/groups/sample_activity_component.html.erb
  app/components/activities/groups/sample_activity_component.rb
  app/components/activities/list_item_component.rb
  app/controllers/activities_controller.rb
  app/controllers/groups/samples_controller.rb
  app/controllers/projects/samples/deletions_controller.rb
  app/controllers/samples/deletions_controller.rb
  app/javascript/controllers/activities/extended_details_controller.js
  app/models/concerns/track_activity.rb
  app/policies/group_policy.rb
  app/services/base_sample_destroy_service.rb
  app/services/groups/samples/destroy_service.rb
  app/services/projects/samples/destroy_service.rb
  app/services/samples/destroy_service.rb
  app/views/groups/samples/index.html.erb
  app/views/projects/samples/deletions/destroy.turbo_stream.erb
  app/views/projects/samples/index.html.erb
  app/views/projects/samples/show.html.erb
  app/views/samples/deletions/_destroy_multiple_confirmation_dialog.html.erb
  app/views/samples/deletions/_destroy_single_confirmation_dialog.html.erb
  app/views/samples/deletions/new.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  config/routes/project.rb
  db/migrate/20250605171908_change_destroy_single_sample_activities.rb
  db/seeds.rb
  db/structure.sql
  test/components/activities/dialogs/activity_list_dialog_component_test.rb
  test/components/activities/dialogs/activity_table_listing_dialog_component_test.rb
  test/components/activity_component_test.rb
  test/components/groups/sample_activity_component_test.rb
  test/components/projects/sample_activity_component_test.rb
  test/components/workflow_execution_activity_component_test.rb
  test/controllers/activities_controller_test.rb
  test/controllers/projects/samples/deletions_controller_test.rb
  test/controllers/samples/deletions_controller_test.rb
  test/fixtures/activity_extended_details.yml
  test/fixtures/extended_details.yml
  test/fixtures/groups.yml
  test/fixtures/members.yml
  test/fixtures/namespace_group_links.yml
  test/fixtures/namespaces/project_namespaces.yml
  test/fixtures/namespaces/user_namespaces.yml
  test/fixtures/projects.yml
  test/fixtures/public_activity/activities.yml
  test/fixtures/routes.yml
  test/fixtures/samples.yml
  test/fixtures/users.yml
  test/models/group_test.rb
  test/policies/group_policy_test.rb
  test/services/groups/samples/destroy_service_test.rb
  test/services/projects/samples/destroy_service_test.rb
  test/services/samples/destroy_service_test.rb
  test/system/dashboard/projects_test.rb
  test/system/groups/samples_test.rb
  test/system/projects/samples_test.rb
Labels: ready for review

#1117 Fix: Back button behaviour
  app/components/data_exports/table_component.rb
  app/components/groups/table_component.rb
  app/components/members/table_component.rb
  app/components/metadata_templates/table_component.rb
  app/components/viral/data_table_component.rb
  app/views/dashboard/projects/index.html.erb
  app/views/groups/activity.html.erb
  app/views/groups/members/index.html.erb
  app/views/projects/activity.html.erb
  app/views/projects/members/index.html.erb
  app/views/projects/samples/attachments/_table.html.erb
  app/views/projects/samples/metadata/_table.html.erb
  app/views/projects/samples/show.html.erb
Labels: accessibility

#1116 feat(navbar): enhance accessibility and localization for dropdown components
  app/components/layout/sidebar_component.html.erb
  app/components/layout_component.html.erb
  app/components/viral/dropdown_component.rb
  config/locales/en.yml
  config/locales/fr.yml
Labels: enhancement, accessibility

#1113 Accessible Treegrid component
  app/assets/tailwind/application.css
  app/components/namespace_row/contents_component.html.erb
  app/components/namespace_row/contents_component.rb
  app/components/namespace_tree/namespace_tree_component.html.erb
  app/components/namespace_tree/namespace_tree_component.rb
  app/components/namespace_tree/row/row_contents_component.html.erb
  app/components/namespace_tree/row/row_contents_component.rb
  app/components/namespace_tree/row/with_children_component.html.erb
  app/components/namespace_tree/row/with_children_component.rb
  app/components/namespace_tree/row/without_children_component.html.erb
  app/components/namespace_tree/row/without_children_component.rb
  app/components/namespace_tree/row_component.rb
  app/components/namespace_tree_container_component.rb
  app/components/treegrid/row_component.rb
  app/components/treegrid_component.rb
  app/controllers/dashboard/groups_controller.rb
  app/controllers/groups/subgroups_controller.rb
  app/javascript/controllers/treegrid_controller.js
  app/views/dashboard/groups/group.turbo_stream.erb
  app/views/dashboard/groups/index.html.erb
  app/views/groups/shared_namespaces/_index.html.erb
  app/views/groups/shared_namespaces/index.turbo_stream.erb
  app/views/groups/subgroups/_index.html.erb
  app/views/groups/subgroups/subgroup.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/components/namespace_tree_component_test.rb
  test/components/previews/treegrid_component_preview.rb
  test/components/previews/treegrid_component_preview/default.html.erb
  test/system/dashboard/groups_test.rb
  test/system/groups_test.rb
  test/test_helpers/w3c_validation_helpers.rb
Labels: accessibility

#1126 Fix: Group creation form description and error message accessibility
  app/assets/tailwind/application.css
  app/controllers/groups_controller.rb
  app/models/concerns/routable.rb
  app/services/groups/create_service.rb
  app/validators/namespace_path_validator.rb
  app/views/groups/_form_fields.html.erb
  app/views/groups/new.html.erb
  app/views/groups/new_subgroup.html.erb
  app/views/shared/form/_field_errors.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  lib/irida/path_regex.rb
  test/graphql/create_group_mutation_test.rb
  test/graphql/create_project_mutation_test.rb
  test/system/groups_test.rb
Labels: accessibility

#1085 Workflow Executions: Mandatory name for user launched workflow executions
  app/components/nextflow_component.html.erb
  app/components/nextflow_component.rb
  app/controllers/concerns/workflow_execution_actions.rb
  app/javascript/controllers/nextflow/samplesheet_controller.js
  app/models/workflow_execution.rb
  app/services/workflow_executions/update_service.rb
  app/views/groups/workflow_executions/update.turbo_stream.erb
  app/views/projects/workflow_executions/update.turbo_stream.erb
  app/views/workflow_executions/update.turbo_stream.erb
  config/locales/en.yml
  config/locales/fr.yml
  test/controllers/workflow_executions_controller_test.rb
  test/fixtures/workflow_executions.yml
  test/models/automated_workflow_execution_test.rb
  test/models/workflow_execution_test.rb
  test/services/workflow_executions/create_service_test.rb
  test/system/projects/workflow_executions_test.rb
  test/system/workflow_executions/submissions_test.rb
  test/system/workflow_executions_test.rb
Labels: enhancement
